import type { QuizQuestion } from '@/lib/quiz/types'

export const THERMO_QUIZ_POOL: QuizQuestion[] = [
  // ===== EASY (8) =====
  {
    id: 'thermo-e1',
    topicId: 'thermodynamics',
    type: 'conceptual',
    question: 'What does temperature measure at the molecular level?',
    options: [
      'Average kinetic energy of molecules',
      'Total number of molecules',
      'Size of molecules',
      'Color of the gas',
    ],
    correctIndex: 0,
    explanation: 'Temperature is a measure of the average translational kinetic energy of molecules (KE = 3/2 kT).',
    difficulty: 'easy',
    classRange: [11, 11],
    showMe: {
      params: { thermoType: 0, temperature: 300, moles: 1, volume: 22.4, molarMass: 28 },
      tab: 'gas',
      layers: ['speedColors'],
      hint: 'Watch the particles - faster motion = higher temperature',
      hintHi: 'कणों को देखें - तेज़ गति = अधिक तापमान',
    },
  },
  {
    id: 'thermo-e2',
    topicId: 'thermodynamics',
    type: 'conceptual',
    question: 'In the ideal gas equation PV = nRT, what does R represent?',
    options: [
      'Universal gas constant (8.314 J/mol K)',
      'Radius of the gas molecule',
      'Rate of expansion',
      'Resistance to compression',
    ],
    correctIndex: 0,
    explanation: 'R is the universal gas constant with value 8.314 J/(mol K). It connects pressure, volume, temperature, and amount of gas.',
    difficulty: 'easy',
    classRange: [11, 11],
  },
  {
    id: 'thermo-e3',
    topicId: 'thermodynamics',
    type: 'conceptual',
    question: 'What is Brownian motion?',
    options: [
      'Random zigzag motion of a large particle due to molecular collisions',
      'Circular motion of gas molecules',
      'Motion of electrons in a conductor',
      'Vibration of atoms in a crystal',
    ],
    correctIndex: 0,
    explanation: 'Brownian motion is the random, erratic movement of a larger particle (like pollen) caused by collisions with smaller, fast-moving gas molecules.',
    difficulty: 'easy',
    classRange: [11, 11],
    showMe: {
      params: { thermoType: 2, temperature: 300, molarMass: 28, numSmall: 80 },
      tab: 'brownian',
      layers: ['speedColors', 'trace'],
      hint: 'The large purple particle is pushed randomly by small molecules',
      hintHi: 'बड़ा बैंगनी कण छोटे अणुओं द्वारा बेतरतीब ढकेला जाता है',
    },
  },
  {
    id: 'thermo-e4',
    topicId: 'thermodynamics',
    type: 'prediction',
    question: 'If you double the temperature of a gas (at constant V and n), the pressure will:',
    options: [
      'Double',
      'Halve',
      'Stay the same',
      'Quadruple',
    ],
    correctIndex: 0,
    explanation: 'From PV = nRT, if V and n are constant, P is directly proportional to T. Doubling T doubles P (Gay-Lussac law).',
    difficulty: 'easy',
    classRange: [11, 11],
    misconception: {
      wrongIndex: 3,
      belief: 'Pressure depends on T squared',
      correction: 'Pressure is linearly proportional to T (P = nRT/V), not T squared. Speed depends on sqrt(T), but pressure depends on T directly.',
    },
  },
  {
    id: 'thermo-e5',
    topicId: 'thermodynamics',
    type: 'conceptual',
    question: 'At absolute zero (0 K), what happens to molecular motion?',
    options: [
      'All molecular motion stops (classically)',
      'Molecules move at the speed of light',
      'Molecules vibrate faster',
      'The gas becomes a plasma',
    ],
    correctIndex: 0,
    explanation: 'At 0 K, classical kinetic theory predicts zero kinetic energy and zero molecular motion. In reality, quantum mechanics allows some zero-point energy.',
    difficulty: 'easy',
    classRange: [11, 11],
  },
  {
    id: 'thermo-e6',
    topicId: 'thermodynamics',
    type: 'conceptual',
    question: 'Which assumption is NOT part of the ideal gas model?',
    options: [
      'Molecules attract each other at close range',
      'Molecules are point particles with negligible volume',
      'Collisions between molecules are perfectly elastic',
      'There are no intermolecular forces except during collisions',
    ],
    correctIndex: 0,
    explanation: 'Ideal gas assumes NO intermolecular forces (no attraction or repulsion). Real gases deviate from ideal behavior precisely because molecules do attract/repel each other.',
    difficulty: 'easy',
    classRange: [11, 11],
  },
  {
    id: 'thermo-e7',
    topicId: 'thermodynamics',
    type: 'prediction',
    question: 'If you add more gas (increase n) to a fixed container at constant T, the pressure will:',
    options: [
      'Increase',
      'Decrease',
      'Stay the same',
      'First increase then decrease',
    ],
    correctIndex: 0,
    explanation: 'From PV = nRT, more moles (n) at constant V and T means higher pressure. More molecules hit the walls more often.',
    difficulty: 'easy',
    classRange: [11, 11],
  },
  {
    id: 'thermo-e8',
    topicId: 'thermodynamics',
    type: 'conceptual',
    question: 'What is the SI unit of pressure?',
    options: [
      'Pascal (Pa)',
      'Joule (J)',
      'Newton (N)',
      'Kelvin (K)',
    ],
    correctIndex: 0,
    explanation: 'Pressure is force per unit area. 1 Pascal = 1 N/m². Standard atmospheric pressure is about 101325 Pa.',
    difficulty: 'easy',
    classRange: [11, 11],
  },

  // ===== MEDIUM (9) =====
  {
    id: 'thermo-m1',
    topicId: 'thermodynamics',
    type: 'calculation',
    question: 'The average kinetic energy of a gas molecule at 300 K is approximately:',
    options: [
      '6.21 x 10⁻²¹ J',
      '6.21 x 10⁻²³ J',
      '6.21 x 10⁻¹⁹ J',
      '6.21 x 10⁻¹⁷ J',
    ],
    correctIndex: 0,
    explanation: 'KE = (3/2)kT = 1.5 x 1.38 x 10⁻²³ x 300 = 6.21 x 10⁻²¹ J. This is the same for ALL ideal gases at the same temperature.',
    solutionSteps: [
      'KE_avg = (3/2) k_B T',
      'KE_avg = 1.5 x 1.38 x 10⁻²³ x 300',
      'KE_avg = 6.21 x 10⁻²¹ J',
    ],
    difficulty: 'medium',
    classRange: [11, 11],
  },
  {
    id: 'thermo-m2',
    topicId: 'thermodynamics',
    type: 'comparison',
    question: 'At the same temperature, which gas has the highest RMS speed?',
    options: [
      'H₂ (M = 2 g/mol)',
      'He (M = 4 g/mol)',
      'N₂ (M = 28 g/mol)',
      'O₂ (M = 32 g/mol)',
    ],
    correctIndex: 0,
    explanation: 'v_rms = sqrt(3RT/M). Lighter molecules move faster. H₂ (M=2) is the lightest, so it has the highest RMS speed.',
    difficulty: 'medium',
    classRange: [11, 11],
    showMe: {
      params: { thermoType: 0, temperature: 300, moles: 1, volume: 22.4, molarMass: 2 },
      tab: 'gas',
      layers: ['speedColors', 'histogram'],
      hint: 'Change molar mass slider to compare different gases',
      hintHi: 'विभिन्न गैसों की तुलना करने के लिए मोलर द्रव्यमान स्लाइडर बदलें',
    },
    misconception: {
      wrongIndex: 2,
      belief: 'Heavier molecules move faster because they have more kinetic energy',
      correction: 'All gases at the same T have the SAME average KE. But KE = (1/2)mv², so lighter molecules must move faster to have the same KE.',
    },
  },
  {
    id: 'thermo-m3',
    topicId: 'thermodynamics',
    type: 'prediction',
    question: 'According to Boyle\'s law, if you compress a gas to half its original volume at constant temperature:',
    options: [
      'Pressure doubles',
      'Pressure halves',
      'Pressure stays the same',
      'Pressure quadruples',
    ],
    correctIndex: 0,
    explanation: 'Boyle\'s law: PV = constant (at fixed T, n). If V is halved, P must double so that PV remains constant.',
    difficulty: 'medium',
    classRange: [11, 11],
    showMe: {
      params: { thermoType: 1, temperature: 300, moles: 1, volume: 22.4, molarMass: 28, pistonPos: 1.0 },
      tab: 'piston',
      layers: ['speedColors', 'pressure'],
      hint: 'Slide the piston to compress - watch the pressure value change',
      hintHi: 'पिस्टन को सरकाकर संपीड़ित करें - दाब मान में बदलाव देखें',
    },
  },
  {
    id: 'thermo-m4',
    topicId: 'thermodynamics',
    type: 'calculation',
    question: 'The RMS speed of N₂ molecules (M = 28 g/mol) at 300 K is approximately:',
    options: [
      '517 m/s',
      '1000 m/s',
      '100 m/s',
      '5170 m/s',
    ],
    correctIndex: 0,
    explanation: 'v_rms = sqrt(3RT/M) = sqrt(3 x 8.314 x 300 / 0.028) = sqrt(267214) = 517 m/s. That is faster than the speed of sound!',
    solutionSteps: [
      'v_rms = sqrt(3RT/M)',
      'M = 28 g/mol = 0.028 kg/mol',
      'v_rms = sqrt(3 x 8.314 x 300 / 0.028)',
      'v_rms = sqrt(267214) = 517 m/s',
    ],
    difficulty: 'medium',
    classRange: [11, 11],
  },
  {
    id: 'thermo-m5',
    topicId: 'thermodynamics',
    type: 'comparison',
    question: 'For an ideal gas, which speed relationship is correct?',
    options: [
      'v_mp < v_avg < v_rms',
      'v_rms < v_avg < v_mp',
      'v_avg < v_mp < v_rms',
      'All three are equal',
    ],
    correctIndex: 0,
    explanation: 'The Maxwell-Boltzmann distribution gives: v_mp (most probable) < v_avg (average) < v_rms (root mean square). The ratios are fixed: v_mp : v_avg : v_rms = 1 : 1.128 : 1.225.',
    difficulty: 'medium',
    classRange: [11, 11],
  },
  {
    id: 'thermo-m6',
    topicId: 'thermodynamics',
    type: 'prediction',
    question: 'If temperature is increased from 300 K to 1200 K, the RMS speed of molecules will:',
    options: [
      'Double (multiply by 2)',
      'Quadruple (multiply by 4)',
      'Triple (multiply by 3)',
      'Increase by 900 m/s',
    ],
    correctIndex: 0,
    explanation: 'v_rms is proportional to sqrt(T). If T goes from 300 to 1200 (4x), v_rms increases by sqrt(4) = 2x.',
    solutionSteps: [
      'v_rms = sqrt(3RT/M)',
      'v_rms is proportional to sqrt(T)',
      'T ratio = 1200/300 = 4',
      'Speed ratio = sqrt(4) = 2',
    ],
    difficulty: 'medium',
    classRange: [11, 11],
    misconception: {
      wrongIndex: 1,
      belief: 'Speed is directly proportional to temperature',
      correction: 'Speed depends on sqrt(T), not T directly. Quadrupling T only doubles the speed.',
    },
  },
  {
    id: 'thermo-m7',
    topicId: 'thermodynamics',
    type: 'conceptual',
    question: 'Why does Brownian motion provide evidence for the existence of molecules?',
    options: [
      'The erratic motion of visible particles can only be explained by invisible molecular bombardment',
      'Brownian motion produces heat',
      'The particles always move in straight lines',
      'It proves molecules are visible under a microscope',
    ],
    correctIndex: 0,
    explanation: 'Robert Brown observed pollen grains jiggling in water. Einstein explained this as proof of molecular bombardment - each random push comes from billions of invisible water molecules.',
    difficulty: 'medium',
    classRange: [11, 11],
  },
  {
    id: 'thermo-m8',
    topicId: 'thermodynamics',
    type: 'calculation',
    question: 'What is the total kinetic energy of 2 moles of an ideal gas at 300 K?',
    options: [
      '7482.6 J',
      '3741.3 J',
      '2494.2 J',
      '14965.2 J',
    ],
    correctIndex: 0,
    explanation: 'Total KE = (3/2)nRT = 1.5 x 2 x 8.314 x 300 = 7482.6 J. This is the total translational kinetic energy.',
    solutionSteps: [
      'KE_total = (3/2) n R T',
      'KE_total = 1.5 x 2 x 8.314 x 300',
      'KE_total = 7482.6 J',
    ],
    difficulty: 'medium',
    classRange: [11, 11],
  },
  {
    id: 'thermo-m9',
    topicId: 'thermodynamics',
    type: 'prediction',
    question: 'A monatomic ideal gas has how many degrees of freedom?',
    options: [
      '3 (translational only)',
      '5 (3 translational + 2 rotational)',
      '6 (3 translational + 3 rotational)',
      '7 (3 translational + 2 rotational + 2 vibrational)',
    ],
    correctIndex: 0,
    explanation: 'Monatomic gases (like He, Ne, Ar) are point particles with no rotational or vibrational modes. They have only 3 translational degrees of freedom (x, y, z).',
    difficulty: 'medium',
    classRange: [11, 11],
  },

  // ===== HARD (8) =====
  {
    id: 'thermo-h1',
    topicId: 'thermodynamics',
    type: 'calculation',
    question: 'The mean free path of N₂ at STP (d = 0.37 nm, T = 273 K, P = 101325 Pa) is approximately:',
    options: [
      '61 nm',
      '93 nm',
      '9.3 nm',
      '610 nm',
    ],
    correctIndex: 0,
    explanation: 'Mean free path = kT/(sqrt(2) pi d² P) = 1.38e-23 x 273 / (sqrt(2) x pi x (0.37e-9)² x 101325) = 3.77e-21 / 6.16e-14 = 6.12 x 10⁻⁸ m ≈ 61 nm.',
    solutionSteps: [
      'lambda = kT / (sqrt(2) pi d² P)',
      'd = 0.37 nm = 3.7 x 10⁻¹⁰ m',
      'Numerator: kT = 1.38e-23 x 273 = 3.77e-21',
      'Denominator: sqrt(2) x pi x (3.7e-10)² x 101325 = 6.08e-19 x 101325 = 6.16e-14',
      'lambda = 3.77e-21 / 6.16e-14 = 6.12e-8 m ≈ 61 nm',
    ],
    difficulty: 'hard',
    classRange: [11, 11],
  },
  {
    id: 'thermo-h2',
    topicId: 'thermodynamics',
    type: 'edge-case',
    question: 'Two containers of different ideal gases at the same T and P are mixed. The average KE per molecule of the mixture is:',
    options: [
      'Same as before mixing (unchanged)',
      'Higher than before',
      'Lower than before',
      'Depends on the molar masses',
    ],
    correctIndex: 0,
    explanation: 'Average KE per molecule = (3/2)kT. It depends ONLY on temperature, not on the type of gas. Since T is the same, mixing does not change the average KE.',
    difficulty: 'hard',
    classRange: [11, 11],
    misconception: {
      wrongIndex: 3,
      belief: 'Heavier molecules have more kinetic energy',
      correction: 'At the same temperature, ALL ideal gas molecules have the same average KE = (3/2)kT, regardless of mass. The mass difference shows up in speed, not energy.',
    },
  },
  {
    id: 'thermo-h3',
    topicId: 'thermodynamics',
    type: 'calculation',
    question: 'If the RMS speed of O₂ (M=32) at 300 K is v, what is the RMS speed of H₂ (M=2) at the same temperature?',
    options: [
      '4v',
      '16v',
      '2v',
      'v/4',
    ],
    correctIndex: 0,
    explanation: 'v_rms is proportional to 1/sqrt(M). Ratio = sqrt(M_O2/M_H2) = sqrt(32/2) = sqrt(16) = 4. So H₂ is 4 times faster.',
    solutionSteps: [
      'v_rms = sqrt(3RT/M)',
      'v_H2 / v_O2 = sqrt(M_O2 / M_H2)',
      '= sqrt(32/2) = sqrt(16) = 4',
      'v_H2 = 4v',
    ],
    difficulty: 'hard',
    classRange: [11, 11],
  },
  {
    id: 'thermo-h4',
    topicId: 'thermodynamics',
    type: 'edge-case',
    question: 'An ideal gas at pressure P and volume V is heated so that both P and V double. The temperature becomes:',
    options: [
      '4T (quadrupled)',
      '2T (doubled)',
      'T (unchanged)',
      '8T',
    ],
    correctIndex: 0,
    explanation: 'PV = nRT. If P becomes 2P and V becomes 2V: (2P)(2V) = nR T_new, so 4PV = nRT_new. Since PV = nRT, T_new = 4T.',
    solutionSteps: [
      'Initial: PV = nRT',
      'Final: (2P)(2V) = nR T_new',
      '4PV = nR T_new',
      'T_new = 4PV/(nR) = 4T',
    ],
    difficulty: 'hard',
    classRange: [11, 11],
  },
  {
    id: 'thermo-h5',
    topicId: 'thermodynamics',
    type: 'comparison',
    question: 'The ratio v_rms : v_avg : v_mp for an ideal gas is:',
    options: [
      'sqrt(3) : sqrt(8/pi) : sqrt(2)',
      'sqrt(2) : sqrt(8/pi) : sqrt(3)',
      '3 : 2 : 1',
      '1 : 1 : 1',
    ],
    correctIndex: 0,
    explanation: 'From Maxwell-Boltzmann: v_rms = sqrt(3RT/M), v_avg = sqrt(8RT/(piM)), v_mp = sqrt(2RT/M). Ratio = sqrt(3) : sqrt(8/pi) : sqrt(2) = 1.732 : 1.596 : 1.414.',
    difficulty: 'hard',
    classRange: [11, 11],
  },
  {
    id: 'thermo-h6',
    topicId: 'thermodynamics',
    type: 'edge-case',
    question: 'At very high pressures, real gases deviate from ideal behavior because:',
    options: [
      'Molecular volume and intermolecular forces become significant',
      'Molecules stop moving',
      'Temperature decreases automatically',
      'The gas constant R changes value',
    ],
    correctIndex: 0,
    explanation: 'At high P, molecules are close together so their finite volume matters and intermolecular forces (van der Waals) become significant. This is why we need the van der Waals equation.',
    difficulty: 'hard',
    classRange: [11, 11],
  },
  {
    id: 'thermo-h7',
    topicId: 'thermodynamics',
    type: 'calculation',
    question: 'The pressure of 3 moles of an ideal gas at 400 K in a 10 L container is:',
    options: [
      '997 kPa',
      '99.7 kPa',
      '9970 kPa',
      '9.97 kPa',
    ],
    correctIndex: 0,
    explanation: 'P = nRT/V = 3 x 8.314 x 400 / 0.01 = 997680 Pa = 997.7 kPa.',
    solutionSteps: [
      'P = nRT/V',
      'V = 10 L = 0.01 m³',
      'P = 3 x 8.314 x 400 / 0.01',
      'P = 997680 Pa = 997.7 kPa',
    ],
    difficulty: 'hard',
    classRange: [11, 11],
  },
  {
    id: 'thermo-h8',
    topicId: 'thermodynamics',
    type: 'edge-case',
    question: 'If Brownian motion were observed to be perfectly smooth (no jiggling), this would imply:',
    options: [
      'Matter is continuous, not made of discrete molecules',
      'Temperature is absolute zero',
      'The particle is too heavy',
      'The microscope is broken',
    ],
    correctIndex: 0,
    explanation: 'Brownian motion exists because matter is granular (made of molecules). If matter were continuous, forces would average to zero from all directions simultaneously, giving smooth motion. Temperature being absolute zero would reduce but not eliminate motion (quantum zero-point energy persists), and a heavy particle would still jiggle, just less noticeably. Only continuous matter eliminates jiggling entirely.',
    difficulty: 'hard',
    classRange: [11, 11],
  },
]
