import type { QuizQuestion } from '@/lib/quiz/types'

export const OPTICS_QUIZ_POOL: QuizQuestion[] = [
  // ===== EASY (8) =====
  {
    id: 'opt-e1',
    topicId: 'optics',
    type: 'conceptual',
    question: 'When light passes from air into glass, it bends:',
    options: ['Away from the normal', 'Toward the normal', 'It does not bend', 'Along the interface'],
    correctIndex: 1,
    explanation: 'Light bends toward the normal when entering a denser medium (higher refractive index). Glass is denser than air.',
    showMe: {
      params: { opticsType: 0, n1: 1.0, n2: 1.5, theta1: 45 },
      tab: 'refraction',
      layers: ['grid', 'rays', 'angles', 'values'],
      hint: 'Notice the refracted ray bends toward the normal (horizontal dashed line) when entering glass.',
      hintHi: 'देखिए कि अपवर्तित किरण काँच में प्रवेश करते समय अभिलम्ब की ओर मुड़ती है।',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 0,
      belief: 'Light always bends away from the normal.',
      correction: 'Light bends TOWARD the normal when entering a denser medium, and AWAY from the normal when entering a rarer medium.',
    },
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-e2',
    topicId: 'optics',
    type: 'conceptual',
    question: 'The refractive index of a vacuum is:',
    options: ['0', '1', '1.5', '2'],
    correctIndex: 1,
    explanation: 'By definition, the refractive index of vacuum is exactly 1. All other materials have n > 1.',
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-e3',
    topicId: 'optics',
    type: 'conceptual',
    question: 'A convex lens is also called a:',
    options: ['Diverging lens', 'Converging lens', 'Flat lens', 'Reflecting lens'],
    correctIndex: 1,
    explanation: 'A convex lens converges (brings together) parallel light rays to a focal point. That is why it is called a converging lens.',
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-e4',
    topicId: 'optics',
    type: 'conceptual',
    question: 'Total internal reflection occurs when light travels from:',
    options: ['Rarer to denser medium', 'Denser to rarer medium', 'Any medium to vacuum', 'Vacuum to any medium'],
    correctIndex: 1,
    explanation: 'TIR only happens when light goes from a denser medium (higher n) to a rarer medium (lower n), AND the angle exceeds the critical angle.',
    showMe: {
      params: { opticsType: 2, n1: 1.5, n2: 1.0, theta1: 45 },
      tab: 'tir',
      layers: ['grid', 'rays', 'angles', 'values'],
      hint: 'Light goes from glass (n=1.5) to air (n=1.0). At 45 degrees (above critical angle of 41.8 degrees), all light is reflected back.',
      hintHi: 'प्रकाश काँच (n=1.5) से हवा (n=1.0) में जाता है। 45 डिग्री पर (क्रांतिक कोण 41.8 डिग्री से ऊपर), सारा प्रकाश वापस परावर्तित होता है।',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-e5',
    topicId: 'optics',
    type: 'conceptual',
    question: 'The SI unit of power of a lens is:',
    options: ['Watt', 'Joule', 'Dioptre', 'Newton'],
    correctIndex: 2,
    explanation: 'The power of a lens is measured in dioptres (D). P = 1/f, where f is the focal length in meters.',
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-e6',
    topicId: 'optics',
    type: 'conceptual',
    question: 'When light hits a surface at 0 degrees (along the normal), the refracted ray:',
    options: ['Bends 90 degrees', 'Goes straight through without bending', 'Reflects back', 'Disappears'],
    correctIndex: 1,
    explanation: 'At normal incidence (0 degrees), sin(0) = 0, so the refracted angle is also 0. Light passes straight through without bending.',
    showMe: {
      params: { opticsType: 0, n1: 1.0, n2: 1.5, theta1: 0 },
      tab: 'refraction',
      layers: ['grid', 'rays', 'angles', 'values'],
      hint: 'At 0 degree incidence, the ray goes straight through. No bending occurs at normal incidence.',
      hintHi: '0 डिग्री आपतन पर, किरण सीधी गुज़रती है। लम्बवत आपतन पर कोई मोड़ नहीं होता।',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-e7',
    topicId: 'optics',
    type: 'conceptual',
    question: 'A concave lens always forms:',
    options: ['A real, inverted image', 'A virtual, erect, diminished image', 'No image', 'A magnified image'],
    correctIndex: 1,
    explanation: 'A concave (diverging) lens always forms a virtual, erect, and diminished image, regardless of object position.',
    showMe: {
      params: { opticsType: 1, objectDist: -30, focalLength: -15, objectHeight: 10 },
      tab: 'lenses',
      layers: ['grid', 'rays', 'values'],
      hint: 'The image (dashed arrow on left) is always virtual, erect, and smaller than the object.',
      hintHi: 'प्रतिबिम्ब (बायीं ओर धराशायी तीर) हमेशा आभासी, सीधा और वस्तु से छोटा होता है।',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-e8',
    topicId: 'optics',
    type: 'conceptual',
    question: 'Mirage is caused by:',
    options: ['Reflection from water', 'Total internal reflection of light in air layers', 'Refraction through glass', 'Diffraction of light'],
    correctIndex: 1,
    explanation: 'Mirages occur due to total internal reflection. Hot air near the ground has a lower refractive index, and light from the sky undergoes TIR in the air layers.',
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },

  // ===== MEDIUM (9) =====
  {
    id: 'opt-m1',
    topicId: 'optics',
    type: 'calculation',
    question: 'Light enters glass (n=1.5) from air at 30 degrees. What is the angle of refraction?',
    options: ['19.5 degrees', '30 degrees', '45 degrees', '60 degrees'],
    correctIndex: 0,
    explanation: 'Using Snell\'s law: sin(theta2) = (n1/n2) * sin(theta1) = (1/1.5) * sin(30) = 0.333. theta2 = arcsin(0.333) = 19.5 degrees.',
    solutionSteps: [
      'Apply Snell\'s law: n1 sin(theta1) = n2 sin(theta2)',
      '1.0 * sin(30) = 1.5 * sin(theta2)',
      'sin(theta2) = sin(30) / 1.5 = 0.5 / 1.5 = 0.333',
      'theta2 = arcsin(0.333) = 19.5 degrees',
    ],
    showMe: {
      params: { opticsType: 0, n1: 1.0, n2: 1.5, theta1: 30 },
      tab: 'refraction',
      layers: ['grid', 'rays', 'angles', 'values'],
      hint: 'See: theta2 = 19.5 degrees. Light bends toward the normal when entering glass.',
      hintHi: 'देखें: theta2 = 19.5 डिग्री। काँच में प्रवेश करते समय प्रकाश अभिलम्ब की ओर मुड़ता है।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-m2',
    topicId: 'optics',
    type: 'calculation',
    question: 'The critical angle for glass (n=1.5) to air is approximately:',
    options: ['30 degrees', '42 degrees', '48 degrees', '60 degrees'],
    correctIndex: 1,
    explanation: 'Critical angle = arcsin(n2/n1) = arcsin(1/1.5) = arcsin(0.667) = 41.8 degrees, approximately 42 degrees.',
    solutionSteps: [
      'Critical angle formula: theta_c = arcsin(n2/n1)',
      'theta_c = arcsin(1.0 / 1.5) = arcsin(0.667)',
      'theta_c = 41.8 degrees, approximately 42 degrees',
    ],
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-m3',
    topicId: 'optics',
    type: 'calculation',
    question: 'An object is placed 30 cm from a convex lens of focal length 15 cm (at 2F). Where is the image?',
    options: ['At 15 cm (at F)', 'At 30 cm (at 2F)', 'At infinity', 'At 10 cm'],
    correctIndex: 1,
    explanation: 'When the object is at 2F, the image forms at 2F on the other side. Using 1/v - 1/u = 1/f: 1/v = 1/15 + 1/(-30) = 1/30. So v = 30 cm.',
    solutionSteps: [
      'u = -30 cm (object on left), f = +15 cm (convex)',
      '1/v = 1/f + 1/u = 1/15 + 1/(-30)',
      '1/v = 2/30 - 1/30 = 1/30',
      'v = 30 cm (real image at 2F on the other side)',
    ],
    showMe: {
      params: { opticsType: 1, objectDist: -30, focalLength: 15, objectHeight: 10 },
      tab: 'lenses',
      layers: ['grid', 'rays', 'values'],
      hint: 'Object at 2F gives image at 2F with magnification = -1 (same size, inverted).',
      hintHi: '2F पर वस्तु रखने पर 2F पर प्रतिबिम्ब बनता है, आवर्धन = -1 (समान आकार, उल्टा)।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-m4',
    topicId: 'optics',
    type: 'prediction',
    question: 'If you increase the angle of incidence from 30 to 60 degrees (air to glass), the refracted angle:',
    options: ['Stays the same', 'Increases', 'Decreases', 'Becomes 90 degrees'],
    correctIndex: 1,
    explanation: 'As the incident angle increases, the refracted angle also increases (both sin values increase). However, the refracted angle is always smaller than the incident angle when going to a denser medium.',
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-m5',
    topicId: 'optics',
    type: 'calculation',
    question: 'What is the power of a convex lens with focal length 20 cm?',
    options: ['+2 D', '+5 D', '+10 D', '+20 D'],
    correctIndex: 1,
    explanation: 'Power = 1/f (in meters) = 1/0.20 = +5 D. Positive power indicates a converging (convex) lens.',
    solutionSteps: [
      'f = 20 cm = 0.20 m',
      'P = 1/f = 1/0.20 = +5 D',
      'Positive sign means converging lens',
    ],
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-m6',
    topicId: 'optics',
    type: 'comparison',
    question: 'Which medium has a higher critical angle with respect to air: water (n=1.33) or glass (n=1.5)?',
    options: ['Glass', 'Water', 'Both have the same', 'Neither has a critical angle'],
    correctIndex: 1,
    explanation: 'Critical angle = arcsin(1/n). Water: arcsin(1/1.33) = 48.8 degrees. Glass: arcsin(1/1.5) = 41.8 degrees. Water has the higher critical angle because it is less dense.',
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-m7',
    topicId: 'optics',
    type: 'prediction',
    question: 'An object is placed between F and a convex lens. The image is:',
    options: ['Real, inverted, magnified', 'Virtual, erect, magnified', 'Real, inverted, diminished', 'No image forms'],
    correctIndex: 1,
    explanation: 'When an object is between F and the lens, the convex lens acts as a magnifying glass. The image is virtual, erect, and magnified. This is how a simple magnifying glass works.',
    showMe: {
      params: { opticsType: 1, objectDist: -10, focalLength: 15, objectHeight: 8 },
      tab: 'lenses',
      layers: ['grid', 'rays', 'values'],
      hint: 'The dashed image arrow on the left is virtual, upright, and bigger than the object.',
      hintHi: 'बायीं ओर धराशायी प्रतिबिम्ब तीर आभासी, सीधा और वस्तु से बड़ा है।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-m8',
    topicId: 'optics',
    type: 'conceptual',
    question: 'Optical fibers work on the principle of:',
    options: ['Refraction', 'Diffraction', 'Total internal reflection', 'Polarization'],
    correctIndex: 2,
    explanation: 'Optical fibers use total internal reflection to carry light signals over long distances. The glass core has a higher refractive index than the cladding, so light undergoes TIR at the boundary.',
    showMe: {
      params: { opticsType: 2, n1: 1.5, n2: 1.0, theta1: 60 },
      tab: 'tir',
      layers: ['grid', 'rays', 'angles', 'values'],
      hint: 'At 60 degrees (well above the critical angle), all light is totally reflected. This is how optical fibers trap light.',
      hintHi: '60 डिग्री पर (क्रांतिक कोण से बहुत ऊपर), सारा प्रकाश पूर्णतः परावर्तित होता है। इसी प्रकार प्रकाशिक तंतु प्रकाश को कैद करते हैं।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-m9',
    topicId: 'optics',
    type: 'calculation',
    question: 'A concave lens has focal length -20 cm. An object is at 30 cm. Where is the image?',
    options: ['-12 cm (virtual)', '+12 cm (real)', '-60 cm (virtual)', '+60 cm (real)'],
    correctIndex: 0,
    explanation: '1/v = 1/f + 1/u = 1/(-20) + 1/(-30) = -3/60 - 2/60 = -5/60 = -1/12. So v = -12 cm (virtual image on same side as object).',
    solutionSteps: [
      'u = -30 cm, f = -20 cm (concave)',
      '1/v = 1/(-20) + 1/(-30)',
      '1/v = -3/60 - 2/60 = -5/60 = -1/12',
      'v = -12 cm (virtual, on same side as object)',
    ],
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },

  // ===== HARD (8) =====
  {
    id: 'opt-h1',
    topicId: 'optics',
    type: 'calculation',
    question: 'Light travels from water (n=1.33) to glass (n=1.5) at 45 degrees. The refracted angle is approximately:',
    options: ['38.8 degrees', '45 degrees', '50.2 degrees', '30 degrees'],
    correctIndex: 0,
    explanation: 'sin(theta2) = (1.33/1.5) * sin(45) = 0.8867 * 0.7071 = 0.627. theta2 = arcsin(0.627) = 38.8 degrees.',
    solutionSteps: [
      'n1 sin(theta1) = n2 sin(theta2)',
      '1.33 * sin(45) = 1.5 * sin(theta2)',
      'sin(theta2) = (1.33 * 0.7071) / 1.5 = 0.627',
      'theta2 = arcsin(0.627) = 38.8 degrees',
    ],
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-h2',
    topicId: 'optics',
    type: 'calculation',
    question: 'An object at 20 cm from a convex lens (f=15 cm) gives a magnification of:',
    options: ['-3', '-2', '+3', '+2'],
    correctIndex: 0,
    explanation: '1/v = 1/15 + 1/(-20) = 4/60 - 3/60 = 1/60. v = 60 cm. m = v/u = 60/(-20) = -3. The image is real, inverted, and 3 times the size.',
    solutionSteps: [
      'u = -20 cm, f = +15 cm',
      '1/v = 1/15 + 1/(-20) = 4/60 - 3/60 = 1/60',
      'v = 60 cm',
      'm = v/u = 60/(-20) = -3 (inverted, magnified 3x)',
    ],
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-h3',
    topicId: 'optics',
    type: 'edge-case',
    question: 'When an object is placed exactly at the focus of a convex lens, the image forms:',
    options: ['At 2F', 'At F on the other side', 'At infinity', 'At the lens'],
    correctIndex: 2,
    explanation: 'When u = -f, the formula gives 1/v = 1/f - 1/f = 0, so v = infinity. The refracted rays are parallel and never converge.',
    showMe: {
      params: { opticsType: 1, objectDist: -15, focalLength: 15, objectHeight: 10 },
      tab: 'lenses',
      layers: ['grid', 'rays', 'values'],
      hint: 'Object at F: rays emerge parallel. Image is at infinity.',
      hintHi: 'फोकस पर वस्तु: किरणें समानांतर निकलती हैं। प्रतिबिम्ब अनंत पर।',
      autoPlay: true,
    },
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-h4',
    topicId: 'optics',
    type: 'calculation',
    question: 'The critical angle for diamond (n=2.42) in air is approximately:',
    options: ['24.4 degrees', '41.8 degrees', '48.8 degrees', '60 degrees'],
    correctIndex: 0,
    explanation: 'theta_c = arcsin(1/2.42) = arcsin(0.413) = 24.4 degrees. This very small critical angle is why diamonds sparkle - light gets trapped easily by TIR.',
    solutionSteps: [
      'theta_c = arcsin(n2/n1) = arcsin(1/2.42)',
      'theta_c = arcsin(0.413) = 24.4 degrees',
      'Small critical angle means more TIR, more sparkle!',
    ],
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-h5',
    topicId: 'optics',
    type: 'comparison',
    question: 'Two lenses: A (f=+10 cm) and B (f=+25 cm). Which has greater power?',
    options: ['Lens B (P=+4 D)', 'Lens A (P=+10 D)', 'Both have the same power', 'Cannot determine'],
    correctIndex: 1,
    explanation: 'Power = 1/f (in meters). Lens A: P = 1/0.10 = +10 D. Lens B: P = 1/0.25 = +4 D. Shorter focal length means greater power.',
    solutionSteps: [
      'Lens A: P = 100/10 = +10 D',
      'Lens B: P = 100/25 = +4 D',
      'Lens A has greater power (shorter focal length = stronger bending)',
    ],
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-h6',
    topicId: 'optics',
    type: 'prediction',
    question: 'As you increase the incident angle from 0 toward the critical angle (denser to rarer), the refracted ray:',
    options: ['Gets closer to the normal', 'Moves away from the normal and approaches 90 degrees', 'Stays at 90 degrees', 'Disappears immediately'],
    correctIndex: 1,
    explanation: 'As the incident angle increases, the refracted angle increases faster (since n1 > n2). At the critical angle, the refracted ray is at exactly 90 degrees (along the interface). Beyond this, TIR occurs.',
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-h7',
    topicId: 'optics',
    type: 'calculation',
    question: 'A convex lens (f=+10 cm) forms a real image of height 4 cm for an object of height 2 cm. The magnification is -2. The object distance is:',
    options: ['-15 cm', '-20 cm', '-10 cm', '-30 cm'],
    correctIndex: 0,
    explanation: 'm = -2, so v/u = -2, meaning v = -2u. Using 1/v - 1/u = 1/f: 1/(-2u) - 1/u = 1/10. Solving: -1/(2u) - 1/u = 1/10, so -3/(2u) = 1/10, giving u = -15 cm.',
    solutionSteps: [
      'm = v/u = -2, so v = -2u',
      '1/v - 1/u = 1/f => 1/(-2u) - 1/u = 1/10',
      '-1/(2u) - 1/u = 1/10',
      '-3/(2u) = 1/10',
      'u = -30/2 = -15 cm',
    ],
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'opt-h8',
    topicId: 'optics',
    type: 'edge-case',
    question: 'When light enters a medium with the SAME refractive index, what happens?',
    options: ['Total internal reflection', 'The light bends at 90 degrees', 'No refraction occurs (straight through)', 'The light is absorbed'],
    correctIndex: 2,
    explanation: 'When n1 = n2, Snell\'s law gives sin(theta2) = sin(theta1), so theta2 = theta1. The light continues in the same direction without any bending.',
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
]
