import type { QuizQuestion } from '@/lib/quiz/types'

export const MODERN_PHYSICS_QUIZ_POOL: QuizQuestion[] = [
  // ===== EASY (9) =====
  {
    id: 'mp-e1',
    topicId: 'modern-physics',
    type: 'conceptual',
    question: 'In the photoelectric effect, electrons are emitted when:',
    options: ['Any light shines on the metal', 'The light frequency exceeds a threshold', 'The metal is heated', 'The light is very intense'],
    correctIndex: 1,
    explanation: 'Electrons are emitted only when the photon frequency exceeds the threshold frequency (f > f0 = phi/h). Below this frequency, no emission occurs regardless of intensity.',
    showMe: {
      params: { modernType: 0, wavelength: 400, workFunction: 2.14, intensity: 50 },
      tab: 'photoelectric',
      layers: ['energyBars'],
      hint: 'Notice: 400 nm light has enough energy (3.1 eV > 2.14 eV) to eject electrons from Cesium.',
      hintHi: 'देखें: 400 nm प्रकाश में पर्याप्त ऊर्जा है (3.1 eV > 2.14 eV) सीज़ियम से इलेक्ट्रॉन निकालने के लिए।',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-e2',
    topicId: 'modern-physics',
    type: 'conceptual',
    question: 'The work function of a metal is:',
    options: ['The energy of the emitted electron', 'The minimum energy needed to free an electron', 'The kinetic energy of the photon', 'The frequency of incident light'],
    correctIndex: 1,
    explanation: 'The work function (phi) is the minimum energy required to remove an electron from the metal surface. It depends on the metal, not the incident light.',
    difficulty: 'easy',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-e3',
    topicId: 'modern-physics',
    type: 'conceptual',
    question: 'In the Bohr model, the ground state of hydrogen has quantum number:',
    options: ['n = 0', 'n = 1', 'n = 2', 'n = infinity'],
    correctIndex: 1,
    explanation: 'The ground state (lowest energy state) of hydrogen corresponds to n = 1. The energy is E1 = -13.6 eV, the most tightly bound state.',
    showMe: {
      params: { modernType: 1, orbitN: 1, atomicZ: 1, transitionFrom: 3, transitionTo: 2 },
      tab: 'bohr',
      layers: ['energyLevels', 'transition'],
      hint: 'The n=1 orbit is closest to the nucleus with the lowest (most negative) energy.',
      hintHi: 'n=1 कक्षा नाभिक के सबसे निकट है और सबसे कम (सबसे ऋणात्मक) ऊर्जा रखती है।',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-e4',
    topicId: 'modern-physics',
    type: 'conceptual',
    question: 'The energy of a photon is given by:',
    options: ['E = mc^2', 'E = hf', 'E = 1/2 mv^2', 'E = qV'],
    correctIndex: 1,
    explanation: 'Photon energy E = hf, where h is Planck\'s constant and f is the frequency. This is the fundamental quantum relation discovered by Planck.',
    difficulty: 'easy',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-e5',
    topicId: 'modern-physics',
    type: 'conceptual',
    question: 'Radioactive decay is:',
    options: ['A chemical reaction', 'A spontaneous nuclear process', 'Caused by external heating', 'Controllable by pressure'],
    correctIndex: 1,
    explanation: 'Radioactive decay is a spontaneous process where unstable nuclei emit radiation to become more stable. It cannot be controlled by external conditions like temperature or pressure.',
    difficulty: 'easy',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-e6',
    topicId: 'modern-physics',
    type: 'conceptual',
    question: 'Half-life is the time for:',
    options: ['All atoms to decay', 'Half the atoms to decay', 'One atom to decay', 'The activity to double'],
    correctIndex: 1,
    explanation: 'Half-life (T1/2) is the time taken for half of the radioactive nuclei in a sample to decay. After one half-life, N = N0/2.',
    showMe: {
      params: { modernType: 2, halfLife: 10, N0: 1000 },
      tab: 'decay',
      layers: ['halfLifeMarkers'],
      hint: 'Watch the decay curve: at each half-life marker, the remaining nuclei halve.',
      hintHi: 'क्षय वक्र देखें: प्रत्येक अर्ध-आयु चिह्न पर, शेष नाभिक आधे हो जाते हैं।',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-e7',
    topicId: 'modern-physics',
    type: 'conceptual',
    question: 'In the Bohr model, electrons can only exist in:',
    options: ['Any orbit', 'Specific allowed orbits', 'The nucleus', 'Free space only'],
    correctIndex: 1,
    explanation: 'Bohr postulated that electrons can only orbit in specific, quantized orbits with angular momentum = nh/2pi. They cannot exist between these orbits.',
    difficulty: 'easy',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-e8',
    topicId: 'modern-physics',
    type: 'conceptual',
    question: 'Which color of light has the highest photon energy?',
    options: ['Red', 'Green', 'Blue', 'Violet'],
    correctIndex: 3,
    explanation: 'Violet light has the shortest wavelength and highest frequency among visible colors. Since E = hf, violet photons carry the most energy.',
    difficulty: 'easy',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-e9',
    topicId: 'modern-physics',
    type: 'conceptual',
    question: 'For a given metal, the stopping potential in the photoelectric effect depends on:',
    options: ['Only intensity of light', 'Only frequency of light', 'Both frequency and intensity', 'Neither frequency nor intensity'],
    correctIndex: 1,
    explanation: 'For a given metal (fixed work function φ), the stopping potential V₀ = (hf − φ)/e depends only on the frequency of incident light. Increasing intensity increases the number of electrons (current) but not their maximum energy.',
    difficulty: 'easy',
    classRange: [12, 12] as [number, number],
  },

  // ===== MEDIUM (9) =====
  {
    id: 'mp-m1',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'The photon energy of 400 nm light is approximately:',
    options: ['1.77 eV', '3.1 eV', '6.2 eV', '13.6 eV'],
    correctIndex: 1,
    explanation: 'E = hc/lambda = (6.626e-34 * 3e8) / (400e-9 * 1.602e-19) = 3.1 eV. This is in the violet/blue region.',
    solutionSteps: [
      'E = hc / lambda',
      'E = (6.626 x 10^-34 x 3 x 10^8) / (400 x 10^-9)',
      'E = 4.97 x 10^-19 J',
      'E = 4.97 x 10^-19 / 1.602 x 10^-19 = 3.1 eV',
    ],
    showMe: {
      params: { modernType: 0, wavelength: 400, workFunction: 2.14, intensity: 50 },
      tab: 'photoelectric',
      layers: ['energyBars'],
      hint: 'The energy bar shows E = 3.10 eV for 400 nm light.',
      hintHi: 'ऊर्जा बार 400 nm प्रकाश के लिए E = 3.10 eV दिखाता है।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-m2',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'For Cesium (phi = 2.14 eV), the threshold wavelength is approximately:',
    options: ['200 nm', '400 nm', '580 nm', '700 nm'],
    correctIndex: 2,
    explanation: 'lambda0 = hc/phi = (6.626e-34 * 3e8) / (2.14 * 1.602e-19) = 580 nm. Light with wavelength above 580 nm cannot eject electrons from Cesium.',
    solutionSteps: [
      'lambda0 = hc / phi',
      'lambda0 = (6.626e-34 * 3e8) / (2.14 * 1.602e-19)',
      'lambda0 = 5.8 x 10^-7 m = 580 nm',
    ],
    difficulty: 'medium',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-m3',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'The energy of an electron in the n=2 orbit of hydrogen is:',
    options: ['-13.6 eV', '-3.4 eV', '-1.51 eV', '-0.85 eV'],
    correctIndex: 1,
    explanation: 'En = -13.6/n^2 eV. For n=2: E2 = -13.6/4 = -3.4 eV. This is the first excited state.',
    solutionSteps: [
      'En = -13.6 / n^2 eV',
      'E2 = -13.6 / (2)^2',
      'E2 = -13.6 / 4 = -3.4 eV',
    ],
    showMe: {
      params: { modernType: 1, orbitN: 2, atomicZ: 1, transitionFrom: 3, transitionTo: 2 },
      tab: 'bohr',
      layers: ['energyLevels', 'transition'],
      hint: 'Look at the energy level diagram: n=2 shows -3.40 eV.',
      hintHi: 'ऊर्जा स्तर चित्र देखें: n=2 पर -3.40 eV दिखता है।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-m4',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'The Bohr radius of the n=3 orbit is:',
    options: ['53 pm', '159 pm', '477 pm', '848 pm'],
    correctIndex: 2,
    explanation: 'rn = n^2 * a0 = 9 * 52.9 pm = 476 pm, approximately 477 pm. The orbit radius scales as n^2.',
    solutionSteps: [
      'rn = n^2 * a0',
      'r3 = 3^2 * 52.9 pm',
      'r3 = 9 * 52.9 = 476 pm',
    ],
    difficulty: 'medium',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-m5',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'After 2 half-lives, what fraction of radioactive nuclei remain?',
    options: ['1/2', '1/4', '1/8', '1/16'],
    correctIndex: 1,
    explanation: 'After each half-life, the number halves. After 2 half-lives: N = N0 * (1/2)^2 = N0/4. So 1/4 of the original nuclei remain.',
    solutionSteps: [
      'After 1 half-life: N = N0/2',
      'After 2 half-lives: N = N0/4',
      'Fraction remaining = 1/4',
    ],
    difficulty: 'medium',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-m6',
    topicId: 'modern-physics',
    type: 'prediction',
    question: 'If the intensity of light above threshold frequency is doubled, the photoelectric current:',
    options: ['Stays the same', 'Doubles', 'Halves', 'Quadruples'],
    correctIndex: 1,
    explanation: 'Doubling intensity doubles the number of photons per second, which doubles the number of ejected electrons per second, hence doubling the current. The KE_max remains unchanged.',
    difficulty: 'medium',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-m7',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'The wavelength of photon emitted in Balmer alpha transition (3 to 2) is approximately:',
    options: ['122 nm', '434 nm', '657 nm', '1875 nm'],
    correctIndex: 2,
    explanation: 'The Balmer alpha line (n=3 to n=2) emits at approximately 657 nm, which is red light. This is why hydrogen emission has a characteristic red line.',
    solutionSteps: [
      'dE = E3 - E2 = (-1.51) - (-3.4) = 1.89 eV',
      'lambda = hc / dE = (6.626e-34 * 3e8) / (1.89 * 1.602e-19)',
      'lambda = 657 nm (red light)',
    ],
    difficulty: 'medium',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-m8',
    topicId: 'modern-physics',
    type: 'prediction',
    question: 'The decay constant lambda is related to half-life by:',
    options: ['lambda = T_half', 'lambda = ln(2) / T_half', 'lambda = 1 / T_half', 'lambda = 2 * T_half'],
    correctIndex: 1,
    explanation: 'lambda = ln(2) / T_half = 0.693 / T_half. A shorter half-life means a larger decay constant (faster decay).',
    difficulty: 'medium',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-m9',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'The maximum KE of electrons emitted from Cs (phi=2.14 eV) by 400 nm light is:',
    options: ['0 eV', '0.96 eV', '2.14 eV', '3.1 eV'],
    correctIndex: 1,
    explanation: 'KE_max = hf - phi = E_photon - phi = 3.1 - 2.14 = 0.96 eV. The excess energy beyond the work function becomes the electron\'s kinetic energy.',
    solutionSteps: [
      'E_photon = hc/lambda = 3.1 eV (for 400 nm)',
      'KE_max = E_photon - phi',
      'KE_max = 3.1 - 2.14 = 0.96 eV',
    ],
    difficulty: 'medium',
    classRange: [12, 12] as [number, number],
  },

  // ===== HARD (9) =====
  {
    id: 'mp-h1',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'For He+ (Z=2), the ground state energy is:',
    options: ['-13.6 eV', '-27.2 eV', '-54.4 eV', '-3.4 eV'],
    correctIndex: 2,
    explanation: 'For a hydrogen-like atom, En = -13.6 * Z^2 / n^2 eV. For He+ (Z=2, n=1): E1 = -13.6 * 4 / 1 = -54.4 eV.',
    solutionSteps: [
      'En = -13.6 * Z^2 / n^2',
      'E1 = -13.6 * (2)^2 / (1)^2',
      'E1 = -13.6 * 4 = -54.4 eV',
    ],
    difficulty: 'hard',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-h2',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'The Lyman alpha transition (2 to 1) emits a photon of wavelength approximately:',
    options: ['122 nm', '364 nm', '657 nm', '91 nm'],
    correctIndex: 0,
    explanation: 'dE = 13.6(1 - 1/4) = 10.2 eV. lambda = hc/dE = 122 nm. This is in the ultraviolet region (Lyman series).',
    solutionSteps: [
      'dE = E1 - E2 = 13.6 * (1 - 1/4) = 10.2 eV',
      'lambda = hc / dE',
      'lambda = (6.626e-34 * 3e8) / (10.2 * 1.602e-19)',
      'lambda = 122 nm (UV)',
    ],
    difficulty: 'hard',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-h3',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'A radioactive sample has 1000 nuclei. After 30 seconds with T_half = 10s, how many remain?',
    options: ['500', '250', '125', '62'],
    correctIndex: 2,
    explanation: '30 seconds = 3 half-lives. N = 1000 * (1/2)^3 = 1000/8 = 125 nuclei.',
    solutionSteps: [
      'Number of half-lives = 30/10 = 3',
      'N = N0 * (1/2)^3',
      'N = 1000 * (1/8) = 125',
    ],
    difficulty: 'hard',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-h4',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'The maximum speed of photoelectrons from Cu (phi=4.65 eV) illuminated by 200 nm UV light is approximately:',
    options: ['0 m/s (no emission)', '5.8 x 10^5 m/s', '7.4 x 10^5 m/s', '2.2 x 10^6 m/s'],
    correctIndex: 2,
    explanation: 'E_photon = hc/200nm = 6.2 eV. KE = 6.2 - 4.65 = 1.55 eV = 2.48e-19 J. v = sqrt(2*KE/me) = sqrt(2*2.48e-19/9.109e-31) = 7.4 x 10^5 m/s.',
    solutionSteps: [
      'E_photon = hc / 200nm = 6.2 eV',
      'KE_max = 6.2 - 4.65 = 1.55 eV = 2.48 x 10^-19 J',
      'v = sqrt(2 * KE / me) = sqrt(2 * 2.48e-19 / 9.109e-31)',
      'v = 7.4 x 10^5 m/s',
    ],
    difficulty: 'hard',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-h5',
    topicId: 'modern-physics',
    type: 'comparison',
    question: 'Which transition emits a photon with the LONGEST wavelength?',
    options: ['3 to 1 (Lyman)', '3 to 2 (Balmer)', '4 to 3 (Paschen)', '2 to 1 (Lyman)'],
    correctIndex: 2,
    explanation: 'Longest wavelength = lowest energy transition. The 4 to 3 transition has dE = 0.66 eV, giving lambda = 1875 nm (infrared). The closer the energy levels, the longer the wavelength.',
    solutionSteps: [
      '3->1: dE = 12.09 eV, lambda = 103 nm',
      '3->2: dE = 1.89 eV, lambda = 657 nm',
      '4->3: dE = 0.66 eV, lambda = 1875 nm (longest)',
      '2->1: dE = 10.2 eV, lambda = 122 nm',
    ],
    difficulty: 'hard',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-h6',
    topicId: 'modern-physics',
    type: 'edge-case',
    question: 'What happens to photoelectrons if you use light just barely above the threshold frequency?',
    options: ['Maximum current flows', 'Electrons are emitted with nearly zero KE', 'No electrons are emitted', 'Electrons are emitted with maximum KE'],
    correctIndex: 1,
    explanation: 'Just above threshold, hf ≈ φ, so KE_max = hf − φ ≈ 0. Electrons are emitted but with almost no kinetic energy. Even a tiny reverse potential would stop them.',
    difficulty: 'hard',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-h7',
    topicId: 'modern-physics',
    type: 'calculation',
    question: 'How long until 75% of a radioactive sample has decayed (T_half = 10s)?',
    options: ['10 s', '15 s', '20 s', '30 s'],
    correctIndex: 2,
    explanation: '75% decayed means 25% remaining = (1/2)^2. So 2 half-lives = 2 * 10 = 20 seconds.',
    solutionSteps: [
      '75% decayed = 25% remaining = 1/4 = (1/2)^2',
      'Number of half-lives = 2',
      'Time = 2 * T_half = 2 * 10 = 20 s',
    ],
    difficulty: 'hard',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-h8',
    topicId: 'modern-physics',
    type: 'comparison',
    question: 'The electron speed in Bohr orbit n=2 compared to n=1 is:',
    options: ['Same speed', 'Half the speed', 'Double the speed', 'One-fourth the speed'],
    correctIndex: 1,
    explanation: 'Electron speed in the Bohr model: vn = v1/n. For n=2: v2 = v1/2. Higher orbits have slower electrons because the Coulomb force is weaker.',
    solutionSteps: [
      'vn = (2.18 x 10^6) / n m/s',
      'v1 = 2.18 x 10^6 m/s',
      'v2 = 2.18 x 10^6 / 2 = 1.09 x 10^6 m/s',
      'v2 = v1 / 2 (half the speed)',
    ],
    difficulty: 'hard',
    classRange: [12, 12] as [number, number],
  },
  {
    id: 'mp-h9',
    topicId: 'modern-physics',
    type: 'edge-case',
    question: 'The Bohr model shown here is a simplification. What is its main limitation?',
    options: ['It only works for hydrogen-like atoms', 'It cannot explain spectral lines', 'It gives wrong energy values', 'It predicts electron mass incorrectly'],
    correctIndex: 0,
    explanation: 'The Bohr model works well for hydrogen and hydrogen-like ions (one electron) but fails for multi-electron atoms. Quantum mechanics (Schrodinger equation) is needed for a complete picture.',
    misconception: {
      wrongIndex: 2,
      belief: 'The Bohr model gives completely wrong energy values.',
      correction: 'For hydrogen, the Bohr model gives excellent energy values. Its limitation is that it only works for single-electron systems.',
    },
    difficulty: 'hard',
    classRange: [12, 12] as [number, number],
  },
]
