import type { QuizQuestion } from '@/lib/quiz/types'

export const QUIZ_POOL: QuizQuestion[] = [
  // ===== EASY (8) =====
  {
    id: 'pm-e1',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'What shape does a projectile trace in the absence of air resistance?',
    options: ['Straight line', 'Parabola', 'Circle', 'Hyperbola'],
    correctIndex: 1,
    explanation: 'A projectile under constant gravity follows a parabolic path.',
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      tab: 'free-play',
      layers: ['grid', 'trajectory'],
      hint: 'Press Play and watch the trail  - it curves into a parabola, not a circle or straight line.',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [6, 8],
  },
  {
    id: 'pm-e2',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'What force acts on a ball after it is thrown (ignoring air)?',
    options: ['The throwing force', 'Gravity only', 'No force', 'Both throwing force and gravity'],
    correctIndex: 1,
    explanation: 'Once released, only gravity acts on the ball. The throwing force stops at release.',
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      tab: 'free-play',
      layers: ['grid', 'trajectory', 'acceleration'],
      hint: 'Watch the Accel arrow  - it only points straight down (gravity). There is no forward force after launch.',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 3,
      belief: 'The throwing force keeps pushing the ball forward.',
      correction: 'Forces require contact. Once the ball leaves your hand, only gravity acts on it.',
    },
    difficulty: 'easy',
    classRange: [6, 8],
  },
  {
    id: 'pm-e3',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'What happens to horizontal speed during projectile flight (no air)?',
    options: ['It increases', 'It decreases', 'It stays constant', 'It becomes zero at the top'],
    correctIndex: 2,
    explanation: 'With no horizontal force, horizontal velocity remains constant throughout.',
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      tab: 'vectors',
      layers: ['grid', 'trajectory', 'components'],
      hint: 'Watch the Vx (horizontal) arrow  - it stays the same length the entire flight. Only Vy changes.',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 3,
      belief: 'The ball slows down completely at the peak.',
      correction: 'Only the vertical speed becomes zero at the peak. Horizontal speed is unchanged.',
    },
    difficulty: 'easy',
    classRange: [6, 10],
  },
  {
    id: 'pm-e4',
    topicId: 'projectile-motion',
    type: 'edge-case',
    question: 'A ball is dropped from rest. What is its horizontal velocity?',
    options: ['9.8 m/s', '0 m/s', 'Depends on height', 'Cannot be determined'],
    correctIndex: 1,
    explanation: 'A ball dropped from rest has zero initial velocity in all directions.',
    showMe: {
      params: { v0: 0, theta: 0, g: 9.8, y0: 20 },
      tab: 'free-play',
      layers: ['grid', 'trajectory', 'components'],
      hint: 'v₀ = 0, so the ball drops straight down. The Vx arrow is zero  - there is no horizontal motion at all.',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [6, 8],
  },
  {
    id: 'pm-e5',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'Which of these is a projectile?',
    options: ['A rocket with engines on', 'A ball thrown in air', 'A plane flying level', 'A car on a road'],
    correctIndex: 1,
    explanation: 'A projectile moves under gravity alone, with no engine or other propulsion.',
    difficulty: 'easy',
    classRange: [6, 8],
  },
  {
    id: 'pm-e6',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'At the highest point, what is the vertical velocity of a projectile?',
    options: ['Maximum', 'Zero', 'Equal to horizontal velocity', 'Negative'],
    correctIndex: 1,
    explanation: 'At the peak, the ball momentarily stops moving upward before falling back down.',
    showMe: {
      params: { v0: 20, theta: 60, g: 9.8, y0: 0 },
      tab: 'vectors',
      layers: ['grid', 'trajectory', 'velocity', 'components'],
      hint: 'Watch the velocity arrow at the peak  - only the horizontal part remains. Vy shrinks to zero at the top.',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [6, 10],
  },
  {
    id: 'pm-e7',
    topicId: 'projectile-motion',
    type: 'prediction',
    question: 'If you throw a ball harder (higher v0), what happens to the range?',
    options: ['Decreases', 'Stays the same', 'Increases', 'Becomes infinite'],
    correctIndex: 2,
    explanation: 'Higher launch speed means the ball travels farther before hitting the ground.',
    showMe: {
      params: { v0: 10, theta: 45, g: 9.8, y0: 0 },
      tab: 'compare',
      compareParams: { v0: 30, theta: 45, g: 9.8, y0: 0 },
      layers: ['grid', 'trajectory'],
      hint: 'Compare: Ball A (v₀=10) vs Ball B (v₀=30), same angle. The faster ball goes much farther.',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [6, 8],
  },
  {
    id: 'pm-e8',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'What is the acceleration of a projectile at its highest point?',
    options: ['Zero', '9.8 m/s² downward', '9.8 m/s² upward', 'It depends on the speed'],
    correctIndex: 1,
    explanation: 'Gravity always pulls downward at 9.8 m/s², even at the peak where velocity is momentarily zero.',
    showMe: {
      params: { v0: 20, theta: 60, g: 9.8, y0: 0 },
      tab: 'vectors',
      layers: ['grid', 'trajectory', 'acceleration', 'velocity'],
      hint: 'Watch the acceleration arrow (red)  - it always points down at the same size, even at the peak where velocity is momentarily zero.',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 0,
      belief: 'Acceleration is zero because the ball stops at the top.',
      correction: 'Velocity is zero at the top, but acceleration due to gravity never stops. That is why the ball comes back down.',
    },
    difficulty: 'easy',
    classRange: [6, 10],
  },

  // ===== MEDIUM (9) =====
  {
    id: 'pm-m1',
    topicId: 'projectile-motion',
    type: 'prediction',
    question: 'At what angle does a projectile travel the farthest (on flat ground)?',
    options: ['30 degrees', '45 degrees', '60 degrees', '90 degrees'],
    correctIndex: 1,
    explanation: '45 degrees gives the maximum range because it balances height and horizontal distance.',
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      tab: 'free-play',
      layers: ['grid', 'trajectory'],
      ghostAngles: [15, 30, 45, 60, 75],
      hint: 'Each trail is a different angle. The 45° trail (middle) lands the farthest  - it perfectly balances height and distance.',
    },
    difficulty: 'medium',
    classRange: [9, 12],
  },
  {
    id: 'pm-m2',
    topicId: 'projectile-motion',
    type: 'comparison',
    question: 'A ball is dropped and another is thrown horizontally from the same height. Which hits the ground first?',
    options: ['The dropped ball', 'The thrown ball', 'They hit at the same time', 'Depends on the throwing speed'],
    correctIndex: 2,
    explanation: 'Horizontal motion does not affect vertical fall. Both have the same vertical acceleration.',
    showMe: {
      params: { v0: 0, theta: 0, g: 9.8, y0: 15 },
      compareParams: { v0: 20, theta: 0, g: 9.8, y0: 15 },
      tab: 'compare',
      layers: ['grid', 'trajectory'],
      hint: 'Press Play  - both balls hit the ground at the exact same time! Horizontal speed does not change how fast something falls.',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 0,
      belief: 'The dropped ball hits first because it goes straight down.',
      correction: 'Vertical and horizontal motions are independent. The thrown ball falls at the same rate.',
    },
    difficulty: 'medium',
    classRange: [9, 12],
  },
  {
    id: 'pm-m3',
    topicId: 'projectile-motion',
    type: 'comparison',
    question: 'On the Moon (g = 1.62 m/s²), a ball thrown at the same speed and angle will:',
    options: ['Go higher and farther', 'Go the same distance', 'Go shorter distance', 'Not move at all'],
    correctIndex: 0,
    explanation: 'Lower gravity means less downward pull, so the ball stays in the air longer and travels farther.',
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      compareParams: { v0: 20, theta: 45, g: 1.62, y0: 0 },
      tab: 'compare',
      layers: ['grid', 'trajectory'],
      hint: 'Ball A is Earth (g=9.8), Ball B is Moon (g=1.62). The Moon ball goes much higher and farther  - weaker gravity means more time in the air.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 12],
  },
  {
    id: 'pm-m4',
    topicId: 'projectile-motion',
    type: 'calculation',
    question: 'A ball is launched at 20 m/s at 45 degrees (g = 9.8 m/s²). What is the approximate max height?',
    options: ['5.1 m', '10.2 m', '20.4 m', '40.8 m'],
    correctIndex: 1,
    explanation: 'Max height = v0² sin²(theta) / (2g) = 400 × 0.5 / 19.6 = 10.2 m.',
    solutionSteps: [
      'Formula: H = v₀² × sin²(θ) / (2g)',
      'v₀ = 20 m/s, θ = 45°, g = 9.8 m/s²',
      'sin(45°) = 0.707, so sin²(45°) = 0.5',
      'H = (20)² × 0.5 / (2 × 9.8)',
      'H = 400 × 0.5 / 19.6',
      'H = 200 / 19.6 = 10.2 m',
    ],
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      tab: 'free-play',
      layers: ['grid', 'trajectory'],
      hint: 'Press Play and watch the max height in the Values panel  - it reads 10.20 m, matching our calculation.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 12],
  },
  {
    id: 'pm-m5',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'Two angles that give the same range on flat ground are called complementary. Which pair works?',
    options: ['30 and 60 degrees', '20 and 80 degrees', '40 and 50 degrees', 'All of the above'],
    correctIndex: 3,
    explanation: 'Any two angles that add up to 90 degrees give the same range (complementary angle theorem).',
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      tab: 'free-play',
      layers: ['grid', 'trajectory'],
      ghostAngles: [30, 40, 50, 60],
      hint: 'Look: 30° and 60° land at the same spot. So do 40° and 50°. Any pair adding to 90° gives equal range!',
    },
    difficulty: 'medium',
    classRange: [9, 12],
  },
  {
    id: 'pm-m6',
    topicId: 'projectile-motion',
    type: 'prediction',
    question: 'If you double the launch speed, the range becomes:',
    options: ['Double', 'Triple', 'Four times', 'Eight times'],
    correctIndex: 2,
    explanation: 'Range = v0² sin(2×theta) / g. Doubling v0 makes v0² four times larger.',
    solutionSteps: [
      'Formula: R = v₀² × sin(2θ) / g',
      'Range depends on v₀ SQUARED',
      'If v₀ doubles: new R = (2v₀)² × sin(2θ) / g',
      '(2v₀)² = 4 × v₀²',
      'So new range = 4 × old range',
    ],
    showMe: {
      params: { v0: 10, theta: 45, g: 9.8, y0: 0 },
      compareParams: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      tab: 'compare',
      layers: ['grid', 'trajectory'],
      hint: 'Ball A: v₀=10 (range ≈ 10.2 m). Ball B: v₀=20 (range ≈ 40.8 m). Double the speed → 4× the range!',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 12],
  },
  {
    id: 'pm-m7',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'The time of flight of a projectile depends on:',
    options: ['Only horizontal velocity', 'Only vertical velocity', 'Both horizontal and vertical velocity', 'Only the mass'],
    correctIndex: 1,
    explanation: 'Time of flight depends only on the vertical component of velocity and gravity.',
    showMe: {
      params: { v0: 10, theta: 45, g: 9.8, y0: 0 },
      compareParams: { v0: 30, theta: 45, g: 9.8, y0: 0 },
      tab: 'compare',
      layers: ['grid', 'trajectory', 'components'],
      hint: 'Both have different speeds but same angle (45°). The faster ball has higher Vy, so it stays airborne longer. Time of flight depends only on Vy and gravity  - not horizontal speed.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 12],
  },
  {
    id: 'pm-m8',
    topicId: 'projectile-motion',
    type: 'comparison',
    question: 'Does a heavier ball fall faster than a lighter one (no air resistance)?',
    options: ['Yes, heavier falls faster', 'No, they fall at the same rate', 'The lighter one falls faster', 'It depends on the shape'],
    correctIndex: 1,
    explanation: 'In vacuum, all objects fall at the same rate regardless of mass. Galileo demonstrated this.',
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      tab: 'free-play',
      layers: ['grid', 'trajectory', 'acceleration'],
      hint: 'Look at the controls  - there is no "mass" slider. That is the point: mass does not appear in projectile equations. A feather and a bowling ball follow this exact path in vacuum. Galileo proved this from the Tower of Pisa!',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 0,
      belief: 'Heavier objects fall faster because they have more weight.',
      correction: 'More mass means more gravitational force, but also more inertia. These cancel out exactly, so acceleration is the same.',
    },
    difficulty: 'medium',
    classRange: [6, 12],
  },
  {
    id: 'pm-m9',
    topicId: 'projectile-motion',
    type: 'calculation',
    question: 'A ball is thrown horizontally at 15 m/s from 10 m height. How far does it land from the base?',
    options: ['15 m', '21.4 m', '30 m', '45 m'],
    correctIndex: 1,
    explanation: 'Fall time = sqrt(2h/g) = sqrt(20/9.8) = 1.43 s. Range = 15 × 1.43 = 21.4 m.',
    solutionSteps: [
      'Horizontal throw: θ = 0°, so all speed is horizontal',
      'Fall time from height h: t = √(2h/g)',
      't = √(2 × 10 / 9.8) = √(2.04) = 1.43 s',
      'Range = Vx × t = 15 × 1.43',
      'Range = 21.4 m',
    ],
    showMe: {
      params: { v0: 15, theta: 0, g: 9.8, y0: 10 },
      tab: 'free-play',
      layers: ['grid', 'trajectory'],
      hint: 'A horizontal throw from 10 m height. Check the Values panel  - Range reads 21.4 m, matching our calculation.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 12],
  },

  // ===== HARD (8) =====
  {
    id: 'pm-h1',
    topicId: 'projectile-motion',
    type: 'calculation',
    question: 'A ball launched at 20 m/s at 30 degrees. What is the horizontal velocity throughout the flight?',
    options: ['10 m/s', '17.3 m/s', '20 m/s', '14.1 m/s'],
    correctIndex: 1,
    explanation: 'vx = v0 × cos(30°) = 20 × 0.866 = 17.3 m/s. It stays constant throughout.',
    solutionSteps: [
      'Horizontal velocity: Vx = v₀ × cos(θ)',
      'v₀ = 20 m/s, θ = 30°',
      'cos(30°) = 0.866',
      'Vx = 20 × 0.866 = 17.3 m/s',
      'No horizontal force → Vx stays 17.3 m/s the whole flight',
    ],
    showMe: {
      params: { v0: 20, theta: 30, g: 9.8, y0: 0 },
      tab: 'vectors',
      layers: ['grid', 'trajectory', 'components'],
      hint: 'Watch the Vx arrow  - it stays exactly the same length (17.3 m/s) from launch to landing. Horizontal velocity never changes.',
      autoPlay: true,
    },
    difficulty: 'hard',
    classRange: [11, 12],
  },
  {
    id: 'pm-h2',
    topicId: 'projectile-motion',
    type: 'calculation',
    question: 'A projectile is launched at 25 m/s at 53 degrees. What is vy at t = 2s? (g = 10 m/s²)',
    options: ['0 m/s', '5 m/s', '10 m/s', '20 m/s'],
    correctIndex: 0,
    explanation: 'vy = v0×sin(53°) - g×t = 25×0.8 - 10×2 = 20 - 20 = 0 m/s. The ball is at its peak.',
    solutionSteps: [
      'Vertical velocity: Vy = v₀ × sin(θ) − g × t',
      'v₀ = 25, θ = 53°, g = 10, t = 2',
      'sin(53°) = 0.8',
      'Vy = 25 × 0.8 − 10 × 2',
      'Vy = 20 − 20 = 0 m/s',
      'Vy = 0 means the ball is at its highest point!',
    ],
    showMe: {
      params: { v0: 25, theta: 53, g: 10, y0: 0 },
      tab: 'vectors',
      layers: ['grid', 'trajectory', 'components'],
      hint: 'Scrub the time slider to t = 2.0 s  - the Vy arrow disappears completely (Vy = 0). The ball is at its peak!',
    },
    difficulty: 'hard',
    classRange: [11, 12],
  },
  {
    id: 'pm-h3',
    topicId: 'projectile-motion',
    type: 'edge-case',
    question: 'A ball is thrown vertically upward at 20 m/s. What is its velocity when it returns to the starting height?',
    options: ['0 m/s', '20 m/s upward', '20 m/s downward', '10 m/s downward'],
    correctIndex: 2,
    explanation: 'By energy conservation, speed at return equals launch speed but direction is reversed.',
    solutionSteps: [
      'Energy conservation: ½mv² is the same at equal heights',
      'At launch: v = 20 m/s upward',
      'At return (same height): speed = 20 m/s',
      'But direction is now downward',
      'Answer: 20 m/s downward',
    ],
    showMe: {
      params: { v0: 20, theta: 90, g: 9.8, y0: 0 },
      tab: 'vectors',
      layers: ['grid', 'trajectory', 'velocity'],
      hint: 'A straight-up throw. Watch the velocity arrow: it shrinks to zero at the top, then grows back to the same size pointing DOWN. Speed at return = launch speed.',
      autoPlay: true,
    },
    difficulty: 'hard',
    classRange: [11, 12],
  },
  {
    id: 'pm-h4',
    topicId: 'projectile-motion',
    type: 'calculation',
    question: 'What is the time of flight for v0 = 20 m/s, theta = 45 degrees, g = 9.8 m/s²?',
    options: ['2.04 s', '2.89 s', '4.08 s', '1.44 s'],
    correctIndex: 1,
    explanation: 'TOF = 2×v0×sin(theta)/g = 2×20×sin(45°)/9.8 = 2×20×0.707/9.8 = 2.89 s.',
    solutionSteps: [
      'Formula: T = 2 × v₀ × sin(θ) / g',
      'v₀ = 20, θ = 45°, g = 9.8',
      'sin(45°) = 0.707',
      'T = 2 × 20 × 0.707 / 9.8',
      'T = 28.28 / 9.8 = 2.89 s',
    ],
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      tab: 'free-play',
      layers: ['grid', 'trajectory'],
      hint: 'Check the Time of Flight in the Values panel  - it reads 2.89 s, exactly matching our formula.',
      autoPlay: true,
    },
    difficulty: 'hard',
    classRange: [11, 12],
  },
  {
    id: 'pm-h5',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'A ball is launched from a cliff (y0 > 0). Compared to flat ground launch, the range:',
    options: ['Increases', 'Decreases', 'Stays the same', 'Depends on the angle only'],
    correctIndex: 0,
    explanation: 'Launching from a height gives more time in the air, increasing the horizontal distance.',
    showMe: {
      params: { v0: 20, theta: 45, g: 9.8, y0: 0 },
      compareParams: { v0: 20, theta: 45, g: 9.8, y0: 15 },
      tab: 'compare',
      layers: ['grid', 'trajectory'],
      hint: 'Ball A: ground level (y₀=0). Ball B: cliff at 15 m (y₀=15). Same speed and angle  - the cliff ball travels much farther because it has extra fall time.',
      autoPlay: true,
    },
    difficulty: 'hard',
    classRange: [11, 12],
  },
  {
    id: 'pm-h6',
    topicId: 'projectile-motion',
    type: 'calculation',
    question: 'A ball launched at 30 m/s at 60 degrees. What is the max height? (g = 10 m/s²)',
    options: ['22.5 m', '33.75 m', '45 m', '67.5 m'],
    correctIndex: 1,
    explanation: 'H = v0² sin²(60°) / (2g) = 900 × 0.75 / 20 = 33.75 m.',
    solutionSteps: [
      'Formula: H = v₀² × sin²(θ) / (2g)',
      'v₀ = 30, θ = 60°, g = 10',
      'sin(60°) = 0.866, sin²(60°) = 0.75',
      'H = (30)² × 0.75 / (2 × 10)',
      'H = 900 × 0.75 / 20',
      'H = 675 / 20 = 33.75 m',
    ],
    showMe: {
      params: { v0: 30, theta: 60, g: 10, y0: 0 },
      tab: 'free-play',
      layers: ['grid', 'trajectory'],
      hint: 'Check Max Height in the Values panel  - it reads 33.75 m, confirming our calculation.',
      autoPlay: true,
    },
    difficulty: 'hard',
    classRange: [11, 12],
  },
  {
    id: 'pm-h7',
    topicId: 'projectile-motion',
    type: 'conceptual',
    question: 'If air resistance is added, which changes more: the range or the max height?',
    options: ['Range decreases more', 'Max height decreases more', 'Both change equally', 'Neither changes'],
    correctIndex: 0,
    explanation: 'Air drag opposes motion throughout, reducing horizontal distance more than peak height.',
    difficulty: 'hard',
    classRange: [11, 12],
  },
  {
    id: 'pm-h8',
    topicId: 'projectile-motion',
    type: 'edge-case',
    question: 'A projectile is launched at 90 degrees (straight up). What is the range?',
    options: ['Maximum possible', 'Zero', 'Undefined', 'Depends on v0'],
    correctIndex: 1,
    explanation: 'At 90 degrees, all velocity is vertical. Horizontal velocity is zero, so range is zero.',
    showMe: {
      params: { v0: 20, theta: 90, g: 9.8, y0: 0 },
      tab: 'free-play',
      layers: ['grid', 'trajectory'],
      hint: 'θ = 90° means straight up. The ball goes up and comes straight back down  - zero horizontal distance. Range = 0.',
      autoPlay: true,
    },
    difficulty: 'hard',
    classRange: [9, 12],
  },
]
