import type { QuizQuestion } from '@/lib/quiz/types'

export const ELEC_QUIZ_POOL: QuizQuestion[] = [
  // ===== EASY (8) =====
  {
    id: 'elec-e1',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'What type of force exists between a positive and a negative charge?',
    options: ['Repulsive', 'Attractive', 'No force', 'Gravitational'],
    correctIndex: 1,
    explanation: 'Opposite charges attract each other. This is the fundamental rule of electrostatics: unlike charges attract, like charges repel.',
    showMe: {
      params: { elecType: 0, q1: 3, q2: -3, distance: 0.5 },
      tab: 'charges',
      layers: ['grid', 'forceVectors', 'values'],
      hint: 'Notice the force arrows pointing inward - the charges pull toward each other.',
      hintHi: 'बल के तीर अंदर की ओर देखें - आवेश एक-दूसरे को खींचते हैं।',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-e2',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'Two positive charges placed near each other will:',
    options: ['Attract each other', 'Repel each other', 'Not interact', 'Orbit each other'],
    correctIndex: 1,
    explanation: 'Like charges repel. Two positive charges push each other apart. The same is true for two negative charges.',
    showMe: {
      params: { elecType: 0, q1: 3, q2: 3, distance: 0.5 },
      tab: 'charges',
      layers: ['grid', 'forceVectors', 'values'],
      hint: 'See the force arrows pointing outward - both positive charges push each other away.',
      hintHi: 'बल के तीर बाहर की ओर देखें - दोनों धन आवेश एक-दूसरे को धकेलते हैं।',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 0,
      belief: 'Positive charges attract because they have charge.',
      correction: 'Only OPPOSITE charges attract. Same-sign charges always repel.',
    },
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-e3',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'What is the SI unit of electric charge?',
    options: ['Volt', 'Coulomb', 'Ampere', 'Ohm'],
    correctIndex: 1,
    explanation: 'The SI unit of electric charge is the Coulomb (C), named after Charles-Augustin de Coulomb who discovered the force law between charges.',
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-e4',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'What does Ohm\'s law state?',
    options: ['V = IR', 'F = ma', 'E = mc²', 'F = qE'],
    correctIndex: 0,
    explanation: 'Ohm\'s law states V = IR, meaning the voltage across a conductor equals the current through it multiplied by its resistance.',
    showMe: {
      params: { elecType: 2, voltage: 9, r1: 100, r2: 100 },
      tab: 'simple-circuit',
      layers: ['grid', 'currentDots', 'values'],
      hint: 'V = IR: with 9V and 100Ω, current I = 9/100 = 0.09A.',
      hintHi: 'V = IR: 9V और 100Ω से, धारा I = 9/100 = 0.09A।',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-e5',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'What is the function of a resistor in a circuit?',
    options: ['Store charge', 'Oppose the flow of current', 'Generate voltage', 'Create magnetic field'],
    correctIndex: 1,
    explanation: 'A resistor opposes (resists) the flow of electric current. Higher resistance means less current flows for the same voltage.',
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-e6',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'Electric field lines point:',
    options: ['From negative to positive', 'From positive to negative', 'In circles around charges', 'Randomly in all directions'],
    correctIndex: 1,
    explanation: 'Electric field lines always point FROM positive charges TO negative charges. They show the direction a positive test charge would move.',
    showMe: {
      params: { elecType: 1, q1: 3, q2: -3, distance: 0.8 },
      tab: 'field-lines',
      layers: ['grid', 'fieldLines'],
      hint: 'See how field lines start at the + charge and curve toward the - charge.',
      hintHi: 'देखें कि क्षेत्र रेखाएँ + आवेश से शुरू होकर - आवेश की ओर मुड़ती हैं।',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-e7',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'What does a battery provide in a circuit?',
    options: ['Resistance', 'Current directly', 'Voltage (potential difference)', 'Charge particles'],
    correctIndex: 2,
    explanation: 'A battery provides a voltage (potential difference) that drives current through the circuit. It does not create charge - it pushes existing charges through the wire.',
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-e8',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'The unit of electrical resistance is:',
    options: ['Ampere', 'Volt', 'Watt', 'Ohm'],
    correctIndex: 3,
    explanation: 'Resistance is measured in Ohms (Ω), named after Georg Simon Ohm. 1 Ohm means 1 Volt of potential difference drives 1 Ampere of current.',
    difficulty: 'easy',
    classRange: [10, 11] as [number, number],
  },

  // ===== MEDIUM (9) =====
  {
    id: 'elec-m1',
    topicId: 'electrostatics',
    type: 'calculation',
    question: 'Two charges q₁ = +2 μC and q₂ = -2 μC are 0.5 m apart. What is the magnitude of the force between them? (k = 9 × 10⁹)',
    options: ['0.072 N', '0.144 N', '0.288 N', '0.036 N'],
    correctIndex: 1,
    explanation: 'F = kq₁q₂/r² = 9×10⁹ × 2×10⁻⁶ × 2×10⁻⁶ / (0.5)² = 9×10⁹ × 4×10⁻¹² / 0.25 = 0.144 N',
    solutionSteps: [
      'F = kq₁q₂/r²',
      'F = 9×10⁹ × 2×10⁻⁶ × 2×10⁻⁶ / (0.5)²',
      'F = 9×10⁹ × 4×10⁻¹² / 0.25',
      'F = 36×10⁻³ / 0.25 = 0.144 N',
    ],
    showMe: {
      params: { elecType: 0, q1: 2, q2: -2, distance: 0.5 },
      tab: 'charges',
      layers: ['grid', 'forceVectors', 'values'],
      hint: 'Check the force value displayed - it should be about 0.14 N.',
      hintHi: 'प्रदर्शित बल मान देखें - यह लगभग 0.14 N होना चाहिए।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-m2',
    topicId: 'electrostatics',
    type: 'prediction',
    question: 'If the distance between two charges is doubled, the electrostatic force becomes:',
    options: ['Half', 'One-quarter', 'Double', 'Four times'],
    correctIndex: 1,
    explanation: 'F ∝ 1/r². If r doubles, F becomes 1/(2²) = 1/4 of the original. The inverse square law means force decreases rapidly with distance.',
    solutionSteps: [
      'F = kq₁q₂/r²',
      'If r → 2r: F\' = kq₁q₂/(2r)²',
      'F\' = kq₁q₂/(4r²) = F/4',
      'Force becomes one-quarter',
    ],
    showMe: {
      params: { elecType: 0, q1: 3, q2: -3, distance: 0.3 },
      compareParams: { elecType: 0, q1: 3, q2: -3, distance: 0.6 },
      tab: 'charges',
      layers: ['grid', 'forceVectors', 'values'],
      hint: 'Compare: at 0.3m the force is ~4× stronger than at 0.6m.',
      hintHi: 'तुलना करें: 0.3m पर बल 0.6m से ~4 गुना अधिक है।',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 0,
      belief: 'If distance doubles, force halves (linear relationship).',
      correction: 'Coulomb\'s law has r² in the denominator. Doubling distance reduces force to 1/4, not 1/2.',
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-m3',
    topicId: 'electrostatics',
    type: 'prediction',
    question: 'If the charge on one object is doubled, the electrostatic force:',
    options: ['Stays the same', 'Doubles', 'Quadruples', 'Halves'],
    correctIndex: 1,
    explanation: 'F = kq₁q₂/r². Force is directly proportional to each charge. Doubling one charge doubles the force.',
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-m4',
    topicId: 'electrostatics',
    type: 'calculation',
    question: 'A 12V battery is connected to a 200Ω resistor. What is the current?',
    options: ['0.06 A', '0.12 A', '2400 A', '24 A'],
    correctIndex: 0,
    explanation: 'Using Ohm\'s law: I = V/R = 12/200 = 0.06 A (60 mA).',
    solutionSteps: [
      'V = IR, so I = V/R',
      'I = 12V / 200Ω',
      'I = 0.06 A = 60 mA',
    ],
    showMe: {
      params: { elecType: 2, voltage: 12, r1: 200, r2: 100 },
      tab: 'simple-circuit',
      layers: ['grid', 'currentDots', 'values'],
      hint: 'The current display shows 0.06 A flowing through the circuit.',
      hintHi: 'धारा प्रदर्शन 0.06 A दिखाता है जो परिपथ में बह रही है।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-m5',
    topicId: 'electrostatics',
    type: 'calculation',
    question: 'Two resistors R₁ = 100Ω and R₂ = 200Ω are connected in series. What is the total resistance?',
    options: ['66.7 Ω', '150 Ω', '300 Ω', '20000 Ω'],
    correctIndex: 2,
    explanation: 'In series, resistances simply add: R_total = R₁ + R₂ = 100 + 200 = 300 Ω.',
    solutionSteps: [
      'Series: R_total = R₁ + R₂',
      'R_total = 100 + 200',
      'R_total = 300 Ω',
    ],
    showMe: {
      params: { elecType: 3, voltage: 9, r1: 100, r2: 200 },
      tab: 'series-parallel',
      layers: ['grid', 'currentDots', 'values'],
      hint: 'The series circuit shows R_total = 300Ω.',
      hintHi: 'श्रेणी परिपथ R_total = 300Ω दिखाता है।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-m6',
    topicId: 'electrostatics',
    type: 'calculation',
    question: 'Two resistors R₁ = 100Ω and R₂ = 100Ω are connected in parallel. What is the total resistance?',
    options: ['200 Ω', '100 Ω', '50 Ω', '25 Ω'],
    correctIndex: 2,
    explanation: 'In parallel: 1/R = 1/R₁ + 1/R₂ = 1/100 + 1/100 = 2/100, so R = 50 Ω. Two equal resistors in parallel give half the resistance.',
    solutionSteps: [
      '1/R_total = 1/R₁ + 1/R₂',
      '1/R_total = 1/100 + 1/100 = 2/100',
      'R_total = 100/2 = 50 Ω',
    ],
    showMe: {
      params: { elecType: 3, voltage: 12, r1: 100, r2: 100 },
      tab: 'series-parallel',
      layers: ['grid', 'currentDots', 'values'],
      hint: 'Parallel R = 50Ω vs Series R = 200Ω. Parallel is always less!',
      hintHi: 'समानांतर R = 50Ω बनाम श्रेणी R = 200Ω। समानांतर हमेशा कम!',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 0,
      belief: 'Parallel means you add the resistances like series.',
      correction: 'Parallel resistors provide ADDITIONAL paths for current, reducing total resistance. The formula is 1/R = 1/R₁ + 1/R₂.',
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-m7',
    topicId: 'electrostatics',
    type: 'comparison',
    question: 'Same battery, same two resistors. Which arrangement draws more current: series or parallel?',
    options: ['Series draws more', 'Parallel draws more', 'Both draw equal current', 'Depends on battery voltage'],
    correctIndex: 1,
    explanation: 'Parallel has lower total resistance (R_p < R_s), so by I = V/R, more current flows. Parallel provides multiple paths for current.',
    showMe: {
      params: { elecType: 3, voltage: 9, r1: 100, r2: 200 },
      tab: 'series-parallel',
      layers: ['grid', 'currentDots', 'values'],
      hint: 'Compare the current values: parallel always has higher current than series.',
      hintHi: 'धारा मानों की तुलना करें: समानांतर में हमेशा श्रेणी से अधिक धारा होती है।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-m8',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'Electric field lines from two positive charges placed close together:',
    options: ['Connect from one to the other', 'Repel and curve away from each other', 'Form circles around both', 'Do not exist'],
    correctIndex: 1,
    explanation: 'Field lines from like charges curve away from each other. They never connect between same-sign charges - they push apart, just like the charges themselves.',
    showMe: {
      params: { elecType: 1, q1: 3, q2: 3, distance: 0.8 },
      tab: 'field-lines',
      layers: ['grid', 'fieldLines'],
      hint: 'See how field lines from both + charges curve outward and away from each other.',
      hintHi: 'देखें कि दोनों + आवेशों की क्षेत्र रेखाएँ बाहर की ओर मुड़कर एक-दूसरे से दूर जाती हैं।',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-m9',
    topicId: 'electrostatics',
    type: 'calculation',
    question: 'A 9V battery powers a 50Ω resistor. What power is dissipated?',
    options: ['0.81 W', '1.62 W', '450 W', '4.5 W'],
    correctIndex: 1,
    explanation: 'P = V²/R = 81/50 = 1.62 W. Or: I = V/R = 0.18A, then P = VI = 9 × 0.18 = 1.62 W.',
    solutionSteps: [
      'I = V/R = 9/50 = 0.18 A',
      'P = V × I = 9 × 0.18',
      'P = 1.62 W',
    ],
    difficulty: 'medium',
    classRange: [10, 11] as [number, number],
  },

  // ===== HARD (8) =====
  {
    id: 'elec-h1',
    topicId: 'electrostatics',
    type: 'calculation',
    question: 'If the distance between two charges is tripled, by what factor does the force change?',
    options: ['1/3', '1/6', '1/9', '1/27'],
    correctIndex: 2,
    explanation: 'F ∝ 1/r². If r → 3r: F\' = F/(3²) = F/9. The force becomes one-ninth.',
    solutionSteps: [
      'F ∝ 1/r²',
      'New distance = 3r',
      'F\' = kq₁q₂/(3r)² = kq₁q₂/(9r²)',
      'F\'/F = 1/9',
    ],
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-h2',
    topicId: 'electrostatics',
    type: 'calculation',
    question: 'R₁ = 100Ω and R₂ = 300Ω in parallel. What is the equivalent resistance?',
    options: ['400 Ω', '200 Ω', '75 Ω', '150 Ω'],
    correctIndex: 2,
    explanation: '1/R = 1/100 + 1/300 = 3/300 + 1/300 = 4/300, so R = 300/4 = 75 Ω.',
    solutionSteps: [
      '1/R = 1/R₁ + 1/R₂',
      '1/R = 1/100 + 1/300',
      '1/R = 3/300 + 1/300 = 4/300',
      'R = 300/4 = 75 Ω',
    ],
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-h3',
    topicId: 'electrostatics',
    type: 'calculation',
    question: 'In a parallel circuit with V = 12V, R₁ = 100Ω, R₂ = 200Ω, what current flows through R₂?',
    options: ['0.04 A', '0.06 A', '0.12 A', '0.18 A'],
    correctIndex: 1,
    explanation: 'In parallel, each resistor has the full voltage across it. I₂ = V/R₂ = 12/200 = 0.06 A.',
    solutionSteps: [
      'In parallel, voltage across each resistor = V',
      'I₂ = V/R₂ = 12/200',
      'I₂ = 0.06 A',
    ],
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-h4',
    topicId: 'electrostatics',
    type: 'calculation',
    question: 'In a series circuit with V = 12V, R₁ = 100Ω, R₂ = 200Ω, what is the voltage across R₁?',
    options: ['4 V', '6 V', '8 V', '12 V'],
    correctIndex: 0,
    explanation: 'In series, I = V/R_total = 12/300 = 0.04 A. Voltage across R₁ = IR₁ = 0.04 × 100 = 4 V.',
    solutionSteps: [
      'R_total = R₁ + R₂ = 100 + 200 = 300 Ω',
      'I = V/R_total = 12/300 = 0.04 A',
      'V₁ = IR₁ = 0.04 × 100 = 4 V',
      'V₂ = IR₂ = 0.04 × 200 = 8 V (check: 4+8 = 12 ✓)',
    ],
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-h5',
    topicId: 'electrostatics',
    type: 'comparison',
    question: 'Coulomb\'s law and Newton\'s law of gravitation both follow inverse square laws. How do they differ?',
    options: [
      'Gravity is always attractive; electric force can attract or repel',
      'They are identical in every way',
      'Electric force follows inverse cube law',
      'Gravity can be repulsive too',
    ],
    correctIndex: 0,
    explanation: 'Both follow F ∝ 1/r², but gravity is always attractive (masses are always positive), while electric force can be attractive or repulsive depending on charge signs.',
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-h6',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'Adding more resistors in parallel to a circuit:',
    options: ['Increases total resistance', 'Decreases total resistance', 'Does not change resistance', 'Doubles the voltage'],
    correctIndex: 1,
    explanation: 'Each parallel resistor adds another path for current, reducing total resistance. Think of it as opening more lanes on a highway - traffic (current) flows more easily.',
    misconception: {
      wrongIndex: 0,
      belief: 'More resistors always means more resistance.',
      correction: 'That is true for series, not parallel. In parallel, more paths = less resistance.',
    },
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-h7',
    topicId: 'electrostatics',
    type: 'conceptual',
    question: 'Why are household appliances connected in parallel, not series?',
    options: [
      'Parallel uses less wire',
      'Each appliance gets the full voltage and works independently',
      'Series circuits are illegal',
      'Parallel circuits use less electricity',
    ],
    correctIndex: 1,
    explanation: 'In parallel, each appliance gets the full mains voltage and can be switched on/off independently. In series, turning off one device would break the circuit for all.',
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
  {
    id: 'elec-h8',
    topicId: 'electrostatics',
    type: 'edge-case',
    question: 'At the exact midpoint between two equal positive charges, the electric field is:',
    options: ['Maximum', 'Zero', 'Pointing upward', 'Undefined'],
    correctIndex: 1,
    explanation: 'The fields from both charges are equal in magnitude but opposite in direction at the midpoint, so they cancel completely. The net field is zero.',
    showMe: {
      params: { elecType: 1, q1: 3, q2: 3, distance: 0.8 },
      tab: 'field-lines',
      layers: ['grid', 'fieldLines'],
      hint: 'Notice how no field lines pass through the exact midpoint - the fields cancel there.',
      hintHi: 'ध्यान दें कि बीच के बिंदु से कोई क्षेत्र रेखा नहीं गुजरती - वहाँ क्षेत्र शून्य हो जाता है।',
      autoPlay: true,
    },
    difficulty: 'hard',
    classRange: [10, 11] as [number, number],
  },
]
