import type { QuizQuestion } from '@/lib/quiz/types'

export const SHM_QUIZ_POOL: QuizQuestion[] = [
  // ===== EASY (8) =====
  {
    id: 'shm-e1',
    topicId: 'shm',
    type: 'conceptual',
    question: 'What type of motion does a pendulum undergo when displaced slightly and released?',
    options: ['Uniform motion', 'Simple harmonic motion', 'Circular motion', 'Random motion'],
    correctIndex: 1,
    explanation: 'A pendulum swings back and forth in a repeating pattern called simple harmonic motion (SHM), where the restoring force is proportional to displacement.',
    showMe: {
      params: { shmType: 0, length: 1, theta0: 15, g: 9.8, damping: 0 },
      tab: 'pendulum',
      layers: ['grid', 'trajectory'],
      hint: 'Watch the pendulum swing back and forth repeatedly - this repeating pattern is SHM.',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-e2',
    topicId: 'shm',
    type: 'conceptual',
    question: 'What is the "time period" of a pendulum?',
    options: [
      'Time to reach the highest point',
      'Time for one complete back-and-forth swing',
      'Time to stop swinging',
      'Time to reach maximum speed',
    ],
    correctIndex: 1,
    explanation: 'The time period (T) is the time taken for one complete oscillation - from one side, to the other, and back again.',
    difficulty: 'easy',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-e3',
    topicId: 'shm',
    type: 'conceptual',
    question: 'At which point in its swing does a pendulum have the maximum speed?',
    options: ['At the extreme positions', 'At the mean (center) position', 'Halfway between center and extreme', 'Speed is constant everywhere'],
    correctIndex: 1,
    explanation: 'The pendulum is fastest at the center (equilibrium) because all potential energy has been converted to kinetic energy at that point.',
    showMe: {
      params: { shmType: 0, length: 1, theta0: 30, g: 9.8, damping: 0 },
      tab: 'pendulum',
      layers: ['grid', 'trajectory', 'velocity'],
      hint: 'Watch the velocity arrow - it is longest at the center and zero at the extremes.',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 0,
      belief: 'The pendulum is fastest at the extremes because it is "trying hardest" to move.',
      correction: 'At the extremes, the pendulum momentarily stops before changing direction. All its energy is potential, not kinetic.',
    },
    difficulty: 'easy',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-e4',
    topicId: 'shm',
    type: 'conceptual',
    question: 'In a spring-mass system, what happens when the spring is compressed and released?',
    options: [
      'The mass moves away and stops',
      'The mass oscillates back and forth',
      'The mass moves in a circle',
      'Nothing happens',
    ],
    correctIndex: 1,
    explanation: 'The spring pushes the mass past the equilibrium point, then pulls it back - this creates an oscillating motion.',
    showMe: {
      params: { shmType: 1, k: 10, mass: 1, amplitude: 0.2, damping: 0 },
      tab: 'spring',
      layers: ['grid', 'trajectory'],
      hint: 'Watch the mass bounce back and forth on the spring - it keeps oscillating.',
      autoPlay: true,
    },
    difficulty: 'easy',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-e5',
    topicId: 'shm',
    type: 'prediction',
    question: 'If you double the length of a pendulum, what happens to its time period?',
    options: ['It doubles', 'It increases by about 41%', 'It stays the same', 'It halves'],
    correctIndex: 1,
    explanation: 'T = 2π√(L/g). Doubling L gives T’ = 2π√(2L/g) = √2 × T ≈ 1.41T, an increase of about 41%.',
    solutionSteps: [
      'T = 2π√(L/g)',
      'New T’ = 2π√(2L/g) = √2 × 2π√(L/g)',
      '√2 ≈ 1.414, so T’ ≈ 1.41 × T',
      'The period increases by about 41%, not doubles',
    ],
    showMe: {
      params: { shmType: 0, length: 2, theta0: 15, g: 9.8, damping: 0 },
      compareParams: { shmType: 0, length: 1, theta0: 15, g: 9.8, damping: 0 },
      tab: 'pendulum',
      layers: ['grid', 'trajectory'],
      hint: 'Compare the 2m pendulum (A) with the 1m pendulum (B) - A is slower but not twice as slow.',
      autoPlay: true,
    },
    misconception: {
      wrongIndex: 0,
      belief: 'Double length means double period.',
      correction: 'Period depends on the SQUARE ROOT of length. Doubling length increases period by √2 ≈ 1.41 times.',
    },
    difficulty: 'easy',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-e6',
    topicId: 'shm',
    type: 'conceptual',
    question: 'Does the mass of the bob affect the time period of a simple pendulum?',
    options: ['Yes, heavier bobs swing slower', 'Yes, heavier bobs swing faster', 'No, mass does not matter', 'Only if the bob is very heavy'],
    correctIndex: 2,
    explanation: 'The time period of a simple pendulum depends only on length (L) and gravity (g), not on the mass of the bob. T = 2π√(L/g).',
    misconception: {
      wrongIndex: 0,
      belief: 'Heavier objects swing slower because they are harder to move.',
      correction: 'While heavier bobs need more force to accelerate, gravity also pulls them harder. These effects cancel out exactly.',
    },
    difficulty: 'easy',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-e7',
    topicId: 'shm',
    type: 'conceptual',
    question: 'What is the "amplitude" of an oscillation?',
    options: [
      'The speed at the center',
      'The maximum displacement from the mean position',
      'The number of oscillations per second',
      'The total distance traveled',
    ],
    correctIndex: 1,
    explanation: 'Amplitude is the maximum distance the oscillating object moves from its equilibrium (mean) position.',
    difficulty: 'easy',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-e8',
    topicId: 'shm',
    type: 'conceptual',
    question: 'What is "frequency" in SHM?',
    options: [
      'The time for one oscillation',
      'The maximum displacement',
      'The number of oscillations per second',
      'The speed of the oscillating object',
    ],
    correctIndex: 2,
    explanation: 'Frequency (f) is the number of complete oscillations per second, measured in Hertz (Hz). It is the inverse of the time period: f = 1/T.',
    difficulty: 'easy',
    classRange: [9, 10] as [number, number],
  },

  // ===== MEDIUM (9) =====
  {
    id: 'shm-m1',
    topicId: 'shm',
    type: 'calculation',
    question: 'A simple pendulum has length 1 m on Earth (g = 9.8 m/s²). What is its time period approximately?',
    options: ['1.0 s', '2.0 s', '3.1 s', '6.3 s'],
    correctIndex: 1,
    explanation: 'T = 2π√(L/g) = 2π√(1/9.8) = 2π × 0.3194 ≈ 2.0 s.',
    solutionSteps: [
      'T = 2π√(L/g)',
      'T = 2π√(1/9.8)',
      'T = 2π × 0.3194',
      'T ≈ 2.01 s ≈ 2.0 s',
    ],
    showMe: {
      params: { shmType: 0, length: 1, theta0: 15, g: 9.8, damping: 0 },
      tab: 'pendulum',
      layers: ['grid', 'trajectory'],
      hint: 'Watch one full swing - it takes about 2 seconds to complete.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-m2',
    topicId: 'shm',
    type: 'comparison',
    question: 'A pendulum on the Moon (g = 1.62 m/s²) vs Earth (g = 9.8 m/s²) with the same length. Which swings slower?',
    options: ['Earth pendulum', 'Moon pendulum', 'Both swing at the same rate', 'Cannot determine without knowing mass'],
    correctIndex: 1,
    explanation: 'Lower gravity means a weaker restoring force, so the pendulum swings more slowly on the Moon. T = 2π√(L/g) - smaller g gives larger T.',
    showMe: {
      params: { shmType: 0, length: 1, theta0: 30, g: 1.62, damping: 0 },
      compareParams: { shmType: 0, length: 1, theta0: 30, g: 9.8, damping: 0 },
      tab: 'pendulum',
      layers: ['grid', 'trajectory'],
      hint: 'Compare Moon pendulum (A, slow) with Earth pendulum (B, fast). The Moon pendulum takes much longer.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-m3',
    topicId: 'shm',
    type: 'calculation',
    question: 'A spring with k = 10 N/m has a 1 kg mass attached. What is the time period of oscillation?',
    options: ['0.63 s', '1.0 s', '1.99 s', '6.28 s'],
    correctIndex: 2,
    explanation: 'T = 2π√(m/k) = 2π√(1/10) = 2π × 0.3162 ≈ 1.99 s.',
    solutionSteps: [
      'T = 2π√(m/k)',
      'T = 2π√(1/10)',
      'T = 2π × 0.3162',
      'T ≈ 1.99 s',
    ],
    showMe: {
      params: { shmType: 1, k: 10, mass: 1, amplitude: 0.2, damping: 0 },
      tab: 'spring',
      layers: ['grid', 'trajectory'],
      hint: 'Watch one full oscillation of the spring-mass system - it takes about 2 seconds.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-m4',
    topicId: 'shm',
    type: 'prediction',
    question: 'If you increase the spring constant (stiffer spring), what happens to the oscillation period?',
    options: ['Period increases', 'Period decreases', 'Period stays the same', 'The mass stops oscillating'],
    correctIndex: 1,
    explanation: 'T = 2π√(m/k). A stiffer spring (larger k) means a smaller ratio m/k, giving a shorter period - it oscillates faster.',
    showMe: {
      params: { shmType: 1, k: 50, mass: 1, amplitude: 0.15, damping: 0 },
      compareParams: { shmType: 1, k: 5, mass: 1, amplitude: 0.15, damping: 0 },
      tab: 'spring',
      layers: ['grid', 'trajectory'],
      hint: 'Stiff spring k=50 (A) bounces much faster than soft spring k=5 (B).',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-m5',
    topicId: 'shm',
    type: 'prediction',
    question: 'If you increase the mass on a spring, what happens to the oscillation period?',
    options: ['Period decreases', 'Period increases', 'Period stays the same', 'Depends on the amplitude'],
    correctIndex: 1,
    explanation: 'T = 2π√(m/k). More mass (larger m) means a larger ratio m/k, giving a longer period - heavier masses oscillate slower.',
    showMe: {
      params: { shmType: 1, k: 10, mass: 5, amplitude: 0.3, damping: 0 },
      compareParams: { shmType: 1, k: 10, mass: 1, amplitude: 0.3, damping: 0 },
      tab: 'spring',
      layers: ['grid', 'trajectory'],
      hint: 'Heavy mass 5kg (A) oscillates slower than light mass 1kg (B) on the same spring.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-m6',
    topicId: 'shm',
    type: 'conceptual',
    question: 'In SHM, when the displacement is maximum (at the extreme), what is the velocity?',
    options: ['Maximum', 'Zero', 'Half of maximum', 'Equal to amplitude'],
    correctIndex: 1,
    explanation: 'At the extreme positions, the object momentarily stops before reversing direction. All energy is potential, and kinetic energy (and therefore velocity) is zero.',
    showMe: {
      params: { shmType: 0, length: 1, theta0: 30, g: 9.8, damping: 0 },
      tab: 'pendulum',
      layers: ['grid', 'trajectory', 'velocity'],
      hint: 'Watch the velocity arrow shrink to zero at each extreme position.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-m7',
    topicId: 'shm',
    type: 'conceptual',
    question: 'What is the relationship between frequency (f) and time period (T)?',
    options: ['f = T', 'f = 2T', 'f = 1/T', 'f = T²'],
    correctIndex: 2,
    explanation: 'Frequency and time period are reciprocals: f = 1/T. If the period is 2 seconds, the frequency is 0.5 Hz (half an oscillation per second).',
    difficulty: 'medium',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-m8',
    topicId: 'shm',
    type: 'conceptual',
    question: 'Why does a damped pendulum eventually stop swinging?',
    options: [
      'Gravity pulls it to rest',
      'The string stretches',
      'Energy is lost to friction and air resistance',
      'The amplitude was too small',
    ],
    correctIndex: 2,
    explanation: 'Damping forces (air resistance, friction at the pivot) continuously convert the pendulum\'s mechanical energy into heat, reducing the amplitude until it stops.',
    showMe: {
      params: { shmType: 0, length: 1, theta0: 30, g: 9.8, damping: 0.3 },
      tab: 'pendulum',
      layers: ['grid', 'trajectory'],
      hint: 'Watch how the swing gets smaller and smaller over time due to damping.',
      autoPlay: true,
    },
    difficulty: 'medium',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-m9',
    topicId: 'shm',
    type: 'prediction',
    question: 'Does the amplitude of a simple pendulum affect its time period (for small angles)?',
    options: ['Yes, larger amplitude means longer period', 'Yes, larger amplitude means shorter period', 'No, period is independent of amplitude', 'Only for very large amplitudes'],
    correctIndex: 2,
    explanation: 'For small angles, the period of a simple pendulum is independent of amplitude. T = 2π√(L/g) has no amplitude term. This is why pendulums were used in clocks!',
    difficulty: 'medium',
    classRange: [9, 10] as [number, number],
  },

  // ===== HARD (8) =====
  {
    id: 'shm-h1',
    topicId: 'shm',
    type: 'calculation',
    question: 'A pendulum clock keeps correct time on Earth. If taken to a planet where g = 4.9 m/s², how will it behave?',
    options: [
      'Clock runs at normal speed',
      'Clock runs faster (gains time)',
      'Clock runs slower (loses time)',
      'Clock stops working',
    ],
    correctIndex: 2,
    explanation: 'With lower g, T = 2π√(L/g) gives a longer period. Each "tick" takes longer, so the clock runs slow and loses time.',
    solutionSteps: [
      'On Earth: T₁ = 2π√(L/9.8)',
      'On planet: T₂ = 2π√(L/4.9)',
      'T₂/T₁ = √(9.8/4.9) = √2 ≈ 1.41',
      'Each tick is 41% longer → clock runs slow, loses time',
    ],
    difficulty: 'hard',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-h2',
    topicId: 'shm',
    type: 'calculation',
    question: 'What length pendulum would have a period of exactly 1 second on Earth (g = 9.8 m/s²)?',
    options: ['0.25 m', '0.50 m', '1.00 m', '2.00 m'],
    correctIndex: 0,
    explanation: 'From T = 2π√(L/g), solving for L: L = gT²/(4π²) = 9.8 × 1²/(4π²) ≈ 0.248 m ≈ 0.25 m.',
    solutionSteps: [
      'T = 2π√(L/g), so L = gT²/(4π²)',
      'L = 9.8 × 1² / (4 × 9.87)',
      'L = 9.8 / 39.48',
      'L ≈ 0.248 m ≈ 0.25 m',
    ],
    difficulty: 'hard',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-h3',
    topicId: 'shm',
    type: 'calculation',
    question: 'Two springs with k = 10 N/m and k = 40 N/m. The 10 N/m spring has mass 1 kg. What mass on the 40 N/m spring gives the SAME period?',
    options: ['0.25 kg', '1 kg', '4 kg', '10 kg'],
    correctIndex: 2,
    explanation: 'For equal periods: √(m₁/k₁) = √(m₂/k₂). So m₂ = m₁ × (k₂/k₁) = 1 × (40/10) = 4 kg.',
    solutionSteps: [
      'T₁ = 2π√(m₁/k₁), T₂ = 2π√(m₂/k₂)',
      'For T₁ = T₂: m₁/k₁ = m₂/k₂',
      'm₂ = m₁ × k₂/k₁ = 1 × 40/10',
      'm₂ = 4 kg',
    ],
    difficulty: 'hard',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-h4',
    topicId: 'shm',
    type: 'edge-case',
    question: 'A pendulum is taken to the International Space Station in microgravity (g ≈ 0). What happens?',
    options: [
      'It swings very slowly',
      'It swings at the same rate',
      'It does not oscillate at all',
      'It swings faster because there is no air resistance',
    ],
    correctIndex: 2,
    explanation: 'A pendulum needs gravity as the restoring force. In microgravity (g ≈ 0), there is no force to pull the bob back, so it will not oscillate. A spring-mass system would still work because it uses elastic force, not gravity.',
    difficulty: 'hard',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-h5',
    topicId: 'shm',
    type: 'comparison',
    question: 'Pendulum A has length 1 m, pendulum B has length 4 m. What is the ratio of their periods T_A : T_B?',
    options: ['1 : 4', '1 : 2', '1 : 16', '2 : 1'],
    correctIndex: 1,
    explanation: 'T ∝ √L. So T_A/T_B = √(1)/√(4) = 1/2. Pendulum B takes twice as long per swing.',
    solutionSteps: [
      'T = 2π√(L/g), so T ∝ √L',
      'T_A/T_B = √(L_A)/√(L_B) = √(1)/√(4)',
      'T_A/T_B = 1/2',
      'Ratio T_A : T_B = 1 : 2',
    ],
    difficulty: 'hard',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-h6',
    topicId: 'shm',
    type: 'conceptual',
    question: 'In SHM, the acceleration is maximum when:',
    options: [
      'The object is at the mean position',
      'The velocity is maximum',
      'The displacement is maximum (at the extreme)',
      'The object is halfway between mean and extreme',
    ],
    correctIndex: 2,
    explanation: 'In SHM, acceleration = -ω²x. Acceleration is proportional to displacement but opposite in direction. Maximum displacement gives maximum acceleration (and zero velocity).',
    difficulty: 'hard',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-h7',
    topicId: 'shm',
    type: 'calculation',
    question: 'A spring-mass system has T = 2 s. If the mass is replaced with one 4 times heavier, what is the new period?',
    options: ['1 s', '2 s', '4 s', '8 s'],
    correctIndex: 2,
    explanation: 'T = 2π√(m/k). If m becomes 4m: T’ = 2π√(4m/k) = 2 × 2π√(m/k) = 2T = 4 s.',
    solutionSteps: [
      'T = 2π√(m/k) = 2 s',
      'New mass = 4m',
      'T’ = 2π√(4m/k) = 2 × 2π√(m/k)',
      'T’ = 2 × T = 2 × 2 = 4 s',
    ],
    difficulty: 'hard',
    classRange: [9, 10] as [number, number],
  },
  {
    id: 'shm-h8',
    topicId: 'shm',
    type: 'conceptual',
    question: 'A spring-mass system works in space but a pendulum does not. Why?',
    options: [
      'Springs are stronger than gravity',
      'Spring restoring force is elastic (not gravitational), so it works without gravity',
      'Pendulums need air to swing',
      'Springs store more energy',
    ],
    correctIndex: 1,
    explanation: 'A spring\'s restoring force comes from the elastic deformation of the spring material (Hooke\'s law: F = -kx). This does not depend on gravity. A pendulum\'s restoring force IS gravity, so it cannot oscillate without it.',
    difficulty: 'hard',
    classRange: [9, 10] as [number, number],
  },
]
